### ISSUE TITLE
How to get lengthOfTimeRange

### ISSUE THREAD

**Issue by tjader** [ecmwf/cfgrib#104]
Hi, I'm trying to understand how I can get the lengthOfTimeRange parameter from an xarray dataset generated by cfgrib.
Working pygrib version:

	import pygrib
	# https://apps.ecmwf.int/codes/grib/format/grib2/ctables/4/4
	# This is the same table as cfgrib.cfmessage.GRIB_STEP_UNITS_TO_SECONDS
	indicatorOfUnitOfTimeRange = {
		0: pd.Timedelta(minutes=1),
		1: pd.Timedelta(hours=1),
		2: pd.Timedelta(days=1),    
		10: pd.Timedelta(hours=3),
		11: pd.Timedelta(hours=6),
		12: pd.Timedelta(hours=12),
		13: pd.Timedelta(seconds=1),
	}

	with pygrib.open(file_path) as grib_file:
		for msg in grib_file:
			time = msg.analDate  # 2019-08-22T18:00:00Z
			valid_date = msg.validDate # # 2019-08-27T18:00:00Z
			time_range = msg.lengthOfTimeRange * indicatorOfUnitOfTimeRange[msg.indicatorOfUnitOfTimeRange]
			
With the attached grib file, I get time_range to be  `pd.Timedelta(hours=3)`.
However, with xarray, I don't seem to be able to get the value.

       import xarray as xr
	ds = xr.open_dataset(file_path, engine='cfgrib')
	# ds.tmin.time 2019-08-22T18:00:00Z
	# ds.tmin.valid_time 2019-08-27T21:00:00Z
	# ds.tmin.step 5 days 3 hours
	(ds.tmin.valid_time - ds.tmin.time) == ds.tmin.step  # True

That is, the valid_time in xarray is the same as valid_date + time_range when opened from pygrib. And the step, is always the time delta between valid_time and time.

Is there any way for me to recover the lengthOfTimeRange variable?

Note: The attached file is a zip compressed grib2 file due to github refusing upload of a plain grib2 (at least for me)
[tmin.zip](https://github.com/ecmwf/cfgrib/files/3724697/tmin.zip)

**Comment by alexamici** [comment]
@tjader did you already try to use `read_keys`? As described here:

https://github.com/ecmwf/cfgrib#read-arbitrary-grib-keys

**Comment by tjader** [comment]
Thank's @alexamici , that'll do.
