### ISSUE TITLE
Can't create file '....grib2.4cc40.idx'

### ISSUE THREAD

**Issue by blaylockbk** [ecmwf/cfgrib#126]
When loading a grib2 file with xarray

    ds = xr.open_dataset('full/path/file.grib2', engine='cfgrib')

I get the error `Can't create file 'full/path/file.grib2.4cc40.idx'`. I believe the reason is because I don't have permission to write to the directory I'm reading the grib file from.

Is there a way to specify a different directory to create the .idx file in? Perhaps be able to write the .idx file in the current working directory?

**Comment by alexamici** [comment]
You can pass the `indexpath` option via `backend_kwargs` as hinted (but not really described) here:

https://github.com/ecmwf/cfgrib#grib-index-file

You can pass a few special format specifiers, e.g. `/tmp/{path}.{short_hash}.idx`
