### ISSUE TITLE
Custom Code Table

### ISSUE THREAD

**Issue by pgierz** [ecmwf/cfgrib#127]
Hello,

Is it possible to load a custom code table for use when opening a Grib dataset with Xarray? I can't seem to find an example of how that would be done. I'd imagine something like this:

```python
ds = xr.open_dataset(
    "/path/to/grb",
     engine="cfgrib", 
    backend_kwargs={"code_table": "/path/to/codetab"}
) 
```

Thanks!
Paul

**Comment by lassiterdc** [comment]
Seconded! I'm having the same exact issue. Without the custom encodings, cfgrib does not recognize the data so I get only na values.

**Comment by iainrussell** [comment]
Hello, see #150 for a bit of a discussion and a solution! The current way is via an environment variable described there (the env var is used by ecCodes, the GRIB engine behind cfgrib). While it could be useful to have this option in cfgrib, we'd have to be careful about how to make it play nicely if the env var is also exported.

Cheers,
Iain

**Comment by pgierz** [comment]
Perhaps to give some additional context: in my particular case, the data is loaded, but has rather silly attributes (e.g. varXZY instead of temp2). A clever person can figure out what is what and hack around this to assign names and whatnot, but that solution is a bit non-optimal, in my view.

I could of course convert everything to NetCDF with cdo. @lassiterdc, not sure if you are (or could be) using this, but it's quite straightforward. For example:
```shell
$ cdo -f nc -t <code_table_file> copy <infile> <outfile>
```
To clarify, the `-f nc` converts the input data to NetCDF, and the `-t` flag assigns "useful" names based upon the code table (see below). Here is where you can [get cdo](https://code.mpimet.mpg.de/projects/cdo/wiki) if it isn't installed on whatever machine you are using. There are a few built-in code tables available, mostly for the Max Planck Institute for Meteorology's (Hamburg, Germany) Atmosphere and Ocean models...

There's also a pretty nifty [python and ruby bridge](https://github.com/Try2Code/cdo-bindings) you may want to take a look at. It supports Xarray, which I've been using in Python for netcdf analysis for the last few years.

Our climate model produces "translation files" , which I marked above with the `<code_table_file>`. Those tend to look like this:

```
 165   1 u10                                                                 0.00    1.00 10m u-velocity [m/s]
 166   1 v10                                                                 0.00    1.00 10m v-velocity [m/s]
 216   1 wimax                                                               0.00    1.00 maximum 10m-wind speed [m/s]
```

First column is the grid variable number, then comes number of (vertical) levels, then the variable name, then 0 and 1 (I haven't figured out what those mean yet), and then what NetCDF would call the "long name", along with units.

@iainrussell: does the env variable support something like that? If so, fantastic!

**Comment by iainrussell** [comment]
Hi @pgierz,

This is the full documentation on what you can do with it and what the tables look like:
https://confluence.ecmwf.int/display/UDOC/Creating+your+own+local+definitions+-+ecCodes+GRIB+FAQ

I believe (not 100% certain) that cdo is using tables formatted for ECMWF's previous GRIB decoding package, GRIBEX, whereas ecCodes is ECMWF's current package for GRIB decoding. I don't think you can use your existing tables with it, you would need to reformat them as shown in the link.

I hope this helps!

Cheers,
Iain

**Comment by iainrussell** [comment]
Hi @aaronspring , you're right, those tables will not work with cfgrib. As you said, cfgrib uses ecCodes to decode GRIB data, and it uses a different format for its tables: https://confluence.ecmwf.int/display/UDOC/Creating+your+own+local+definitions+-+ecCodes+GRIB+FAQ

**Comment by pgierz** [comment]
Would there be interest in a conversion tool? I know it's a pretty special edge case, but I could look at putting one together; maybe @aaronspring you have more insight than I do, but I suspect the out coming MPI-Met models will be CDO friendly again, so having some way of going to the custom CDO table format to one that also fits with the general scheme would be nice to have...

**Comment by pgierz** [comment]
....oh that is super hacky. I like the idea though 👍🏻 Perhaps one could consider using the extension policy of xarray? Not sure if you know about this or not, but have a look here: https://xarray.pydata.org/en/stable/internals/extending-xarray.html

**Comment by aaronspring** [comment]
Whether using a function or wrapping it with the internals, I don't mind. The function needs an xr.Dataset and the path to the codes file as input IMO. 

Recently had chat with https://github.com/moritz-g about this topic and we decided it's not a priority for us, but would contribute.

**Comment by pgierz** [comment]
@aaronspring, in general I agree: how we actually do it isn't so important. It would IMO be nice to be able to provide the community with some sort of easy-to-use solution (and more importantly, easy-to-discover!); but I believe the topic we have specifically in mind (e.g. GRB, CDO, and related code tables) is out of scope here. To work on the xarray extension idea, I started https://github.com/pydata/xarray/discussions/6622. Also, if there any "let's make climate model output more friendly" meetings you are involved in, please let me know! pgierz@awi.de 

So, if no one minds, I will close this issue. There is enough posted info I believe for other people who might stumble across this to get started.
