### ISSUE TITLE
What can be done when a `paramId_0` Data variable name is returned?

### ISSUE THREAD

**Issue by blaylockbk** [ecmwf/cfgrib#128]
(Sorry to keep asking usage questions here if this isn't the best place, but I'm not sure where else to ask. I appreciate the help.)

I'm reading a grib2 file that includes the Dew Point Depression (DEPR) variable. 
```
wgrib2 sample.grib2 -v1

1:0:d=2016052000:TMP Temperature [K]:1000 mb:anl:
2:53364:d=2016052000:DEPR Dew Point Depression (or Deficit) [K]:1000 mb:anl:
3:99792:d=2016052000:DPT Dew Point Temperature [K]:1000 mb:anl:
4:130092:d=2016052000:HGT Geopotential Height [gpm]:1000 mb:anl:
5:171896:d=2016052000:RH Relative Humidity [%]:1000 mb:anl:
6:225260:d=2016052000:UGRD U-Component of Wind [m/s]:1000 mb:anl:
7:271688:d=2016052000:VAPP Vapour Pressure [Pa]:1000 mb:anl:
8:313492:d=2016052000:VGRD V-Component of Wind [m/s]:1000 mb:anl:
9:359920:d=2016052000:DZDT Vertical Velocity (Geometric) [m/s]:1000 mb:anl:
```

But when I read it with cfgrib, the DEPR field is returned as the variable name `paramId_0`.

```
import xarray as xr
sample.xr.open_dataset('sample.grib2', engine='cfgrib')

<xarray.Dataset>
Dimensions:        (x: 70, y: 70)
Coordinates:
    time           datetime64[ns] ...
    step           timedelta64[ns] ...
    isobaricInhPa  int64 ...
    latitude       (y, x) float64 ...
    longitude      (y, x) float64 ...
    valid_time     datetime64[ns] ...
Dimensions without coordinates: x, y
Data variables:
    t              (y, x) float32 ...
    paramId_0      (y, x) float32 …   <--- This is the DEPR variable
    dpt            (y, x) float32 ...
    gh             (y, x) float32 ...
    r              (y, x) float32 ...
    u              (y, x) float32 ...
    vapp           (y, x) float32 ...
    v              (y, x) float32 ...
    wz             (y, x) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             fnmo
    GRIB_centreDescription:  US Navy - Fleet Numerical Oceanography Center
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US Navy - Fleet Numerical Oceanography Center
    history:                 2020-03-10T17:43:53 GRIB to CDM+CF via cfgrib-0....
```

Also, `sample.paramId_0` has no shortName, units, name, cf_name, cf_VarName. 

I suspect this information about DEPR is missing in the grib message because when I read the file with pygrib and try to print out those same values, units, name, cfName, etc. are all "unknown". I checked the [list of grib parameters](https://apps.ecmwf.int/codes/grib/param-db/), and DEPR is not included in grib2. Does that have anything to do with why it doesn't include metadata for units and name? 
![image](https://user-images.githubusercontent.com/6249613/76341239-fcebb900-62b9-11ea-9147-dd9b33f465d1.png)

Is there a way to tell cfgrib what the variable name and units should be (maybe by updating a dict or list)? Or would this need to be manually changed in the xarray DataArray structure?

**Comment by iainrussell** [comment]
Hi @blaylockbk , yes, the fact that the Parameter Database does not have this parameter for GRIB 2 very strongly suggests that ecCodes, the GRIB decoder used by cfgrib, also will not have the parameter. The command-line tools that come with ecCodes (grib_ls, grib_dump) should be able to verify this. One possibility is to add your own table that ecCodes can see, as described here:
https://confluence.ecmwf.int/display/UDOC/Creating+your+own+local+definitions+-+ecCodes+GRIB+FAQ
