### ISSUE TITLE
error opening grib2 dataset 

### ISSUE THREAD

**Issue by GloryPassarello** [ecmwf/cfgrib#132]
I am trying to open a `GRIB2 `dataset using `cfgrib` engine with python but I got this error:
```
DatasetBuildError: multiple values for unique key, try re-open the file with one of:
    filter_by_keys={'typeOfLevel': 'unknown'}
    filter_by_keys={'typeOfLevel': 'heightAboveGround'}
    filter_by_keys={'typeOfLevel': 'surface'}
```

when I try to re-open the file as suggested on the error I got back: 

`TypeError: open_dataset() got an unexpected keyword argument 'filter_by_keys'`

the version of eccodes I am using: 

```
python -m eccodes selfcheck
Found: ecCodes v2.17.0.
Your system is ready.
```
and 
`cfgrib==0.9.8.1`

**Comment by alexamici** [comment]
When using `xr.open_dataset` you need to pass options inside the `backend_kwargs` argument:
`>>> xr.open_dataset('file.grib', engine='cfgrib', backend_kwargs=dict(filter_by_keys={'typeOfLevel': 'surface'}))`

**Comment by GloryPassarello** [comment]
It works like a charm. Thanks!
