### ISSUE TITLE
OSError: ctypes.util.find_library() did not manage to locate a library called 'libeccodes'

### ISSUE THREAD

**Issue by RattanaChhin** [ecmwf/cfgrib#144]
Dear developers, 

I am trying to install the cfgrib on anacond3 in window 10 system. 
I have successfully installed the package using command "pip install cfgrib". 
However, when I try to call the package to the workspace, I got the following errors. 

_####################################################################
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\cfgrib\bindings.py", line 48, in <module>
    lib = ffi.dlopen(libname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: ctypes.util.find_library() did not manage to locate a library called 'libeccodes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\cfgrib\messages.py", line 37, in <module>
    from . import bindings as eccodes
  File "C:\ProgramData\Anaconda3\lib\site-packages\cfgrib\bindings.py", line 86, in <module>
    CODES_TYPE_UNDEFINED = lib.GRIB_TYPE_UNDEFINED
  File "C:\ProgramData\Anaconda3\lib\site-packages\cfgrib\bindings.py", line 43, in __getattr__
    raise RuntimeError(self.message) from self.exc
RuntimeError: ecCodes library not found on the system.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cfgrib\__init__.py", line 19, in <module>
    from .cfmessage import CfMessage
  File "C:\ProgramData\Anaconda3\lib\site-packages\cfgrib\cfmessage.py", line 29, in <module>
    from . import messages
  File "C:\ProgramData\Anaconda3\lib\site-packages\cfgrib\messages.py", line 39, in <module>
    import pyeccodes.compat as eccodes
ModuleNotFoundError: No module named 'pyeccodes'
##############################################################_

Can you suggest how to solve this problem on above-mentioned system? 

Thank you.

**Comment by alexamici** [comment]
The suggested install procedure for Windows is via *conda-forge* as described in the README:

`$ conda install -c cpnda-forge cfgrib`

Please report back if it solves the problem for you.

**Comment by RattanaChhin** [comment]
Hello Alexamici, 

Thank you very much. 

When I try your command above, I get the following results. 

_**############################################
(base) C:\Windows\system32>conda install -c cpnda-forge cfgrib
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: cpnda-forge
  channel url: https://conda.anaconda.org/cpnda-forge
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

#############################################################**_






In fact, before install the package with "pip install", I also try to install the package using conda command ("conda install -c conda-forge cfgrib") as well, but it cannot solve environment. 
I get the following results. 

#################################################################
(base) C:\Windows\system32>conda install -c conda-forge cfgrib
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining multipledispatch:   5%|██▊                                                  | 17/317 [00:10<01:48,  2.77it/s]|Examining pyflakes:   9%|█████▏                                                       | 27/317 [00:17<05:04,  1.05s/it]|Examining anaconda-navigator:  15%|███████▍                                           | 46/317 [00:27<03:29,  1.29it/-
##########################################################################



Seem conda try to solve some conflicts by examining the internal package in conda.
However, after this process it still cannot be installed.

**Comment by RattanaChhin** [comment]
Hello Alexamici, 

Thank you very much. 
Following your command, I can install it now. 

It is a great support.
