### ISSUE TITLE
Problem installing cfgrib via conda - module 'pyeccodes.compat' has no attribute

### ISSUE THREAD

**Issue by shimonw2** [ecmwf/cfgrib#147]
![image](https://user-images.githubusercontent.com/66849514/84546895-5c4dd080-acd0-11ea-8fcd-1bc39acd9d81.png)

**Comment by alexamici** [comment]
*pyeccodes* is a highly experimental new package. Do not install it. Please uninstall it and try again.

**Comment by shimonw2** [comment]
Thanks for the feedback. I ended up not using cfgrib, as it didn’t work for me.

Shimon


******************************************************************
Dr. Shimon Wdowinski
Department of Earth and Environment
Florida International University
11200 SW 8th Street, AHC5-388
Miami, FL 33199

Office: 305-348-6826
Cell:    305-607-1603
e-mail: shimon.wdowinski@fiu.edu<mailto:shimon.wdowinski@fiu.edu>

Website: http://faculty.fiu.edu/~swdowins/index.html
******************************************************************

On Sep 15, 2020, at 7:02 AM, alexamici <notifications@github.com<mailto:notifications@github.com>> wrote:


Note: This message originated from outside the FIU Faculty/Staff email system.



pyeccodes is a highly experimental new package. Do not install it. Please uninstall it and try again.

**Comment by cdibble** [comment]
This is an ongoing issue for me. If I have the binary dependencies installed via `sudo apt-get install libeccodes0` , then after `pip install cfgrib`, I can import `cfgrib` and work with it. This works for python3.6 on Ubuntu 18.x.

However, if I try to package that and deploy it in a serverless (AWS Lambda) environment, I cannot `import cfgrib` and instead get an error: No module named 'pyeccodes'. If I include that module as part of the deployment package, then I end up with the same `module pyeccodes.compat has no attribute...` error. 

Does anyone have a better understanding of these dependencies? Is it not possible to package cfgrib for use in a serverless environment? 

@alexamici perhaps you have an idea? Is there some way to eliminate or resolve the dependency on `pyeccodes`?
