### ISSUE TITLE
Issue while opening KNMI Harmonie-Arome output

### ISSUE THREAD

**Issue by meteoDaniel** [ecmwf/cfgrib#150]
I am using the open data files proviede by KNMI under open data policy. Data can be downloaded under [06_RUN](https://data.knmi.nl/download/harmonie_arome_cy40_p3/0.2/noversion/0000/00/00/harm40_v1_p3_06.tar)

```
data = xarray.open_dataset('HA40_N55_202006030600_03900_GB', engine='cfgrib', backend_kwargs={'filter_by_keys':{'typeOfLevel': 'heightAboveGround','level': 10, 'stepType': 'instant'}})
```
At least only one variables named `paramId_0`  is listed in the Dataset. 
Why does cfgrib does not detect all available variables?

Maybe the solution is to force cfgrib to use `NCEP-opn` parameter table as `wgrib` does. But I am not really familiar with the cfgrib backend. 

xarray.__version__: 0.15.1
cfgrib.__version__: 0.9.8.2

Output of `wgrib -v `:

``` 
Undefined parameter table (center 99-0 table 253), using NCEP-opn
1:0:D=2020060306:PRES:0 m above MSL:kpds=1,103,0:47hr fcst:winds in grid direction:"Pressure [Pa]
2:347422:D=2020060306:TMP:2 m above gnd:kpds=11,105,2:47hr fcst:winds in grid direction:"Temp. [K]
3:579244:D=2020060306:RH:2 m above gnd:kpds=52,105,2:47hr fcst:winds in grid direction:"Relative humidity [%]
4:811066:D=2020060306:DPT:2 m above gnd:kpds=17,105,2:47hr fcst:winds in grid direction:"Dew point temp. [K]
5:1158488:D=2020060306:UGRD:10 m above gnd:kpds=33,105,10:47hr fcst:winds in grid direction:"u wind [m/s]
6:1390310:D=2020060306:VGRD:10 m above gnd:kpds=34,105,10:47hr fcst:winds in grid direction:"v wind [m/s]
7:1622132:D=2020060306:CSULF:10 m above gnd:kpds=162,105,10:valid 0-47hr:winds in grid direction:"Clear sky upward long wave flux [W/m^2]
8:1853954:D=2020060306:CSDLF:10 m above gnd:kpds=163,105,10:valid 0-47hr:winds in grid direction:"Clear sky downward long wave flux [W/m^2]
9:2085776:D=2020060306:NSWRS:0 m above gnd:kpds=111,105,0:0-47hr acc:winds in grid direction:"Net short wave (surface) [W/m^2]
10:2317598:D=2020060306:NLWRS:0 m above gnd:kpds=112,105,0:0-47hr acc:winds in grid direction:"Net long wave (surface) [W/m^2]
11:2549420:D=2020060306:4LFTX:0 m above gnd:kpds=132,105,0:0-47hr acc:winds in grid direction:"Best (4-layer) lifted index [K]
12:2781242:D=2020060306:GRAD:0 m above gnd:kpds=117,105,0:0-47hr acc:winds in grid direction:"Global radiation [W/m^2]
13:3013064:D=2020060306:LAND:0 m above gnd:kpds=81,105,0:47hr fcst:winds in grid direction:"Land cover (land=1;sea=0) [fraction]
14:3244886:D=2020060306:TCDC:0 m above gnd:kpds=71,105,0:47hr fcst:winds in grid direction:"Total cloud cover [%]
15:3476708:D=2020060306:HCDC:0 m above gnd:kpds=75,105,0:47hr fcst:winds in grid direction:"High level cloud cover [%]
16:3708530:D=2020060306:MCDC:0 m above gnd:kpds=74,105,0:47hr fcst:winds in grid direction:"Mid level cloud cover [%]
17:3940352:D=2020060306:LCDC:0 m above gnd:kpds=73,105,0:47hr fcst:winds in grid direction:"Low level cloud cover [%]
18:4172174:D=2020060306:MIXHT:0 m above gnd:kpds=67,105,0:47hr fcst:winds in grid direction:"Mixed layer depth [m]
19:4403996:D=2020060306:GP:0 m above gnd:kpds=6,105,0:47hr fcst:winds in grid direction:"Geopotential [m^2/s^2]
20:4751418:D=2020060306:VIS:0 m above gnd:kpds=20,105,0:47hr fcst:winds in grid direction:"Visibility [m]
21:5098840:D=2020060306:SNOD:0 m above gnd:kpds=66,105,0:47hr fcst:winds in grid direction:"Snow depth [m]
22:5314620:D=2020060306:LPSX:0 m above gnd:kpds=181,105,0:47hr fcst:winds in grid direction:"x-gradient of log pressure [1/m]
23:5546442:D=2020060306:HGTY:0 m above gnd:kpds=184,105,0:47hr fcst:winds in grid direction:"y-gradient of height [m/m]
24:5778264:D=2020060306:ICWAT:0 m above gnd:kpds=201,105,0:47hr fcst:winds in grid direction:"Ice-free water surface [%]
25:6010086:D=2020060306:LPSX:0 m above gnd:kpds=181,105,0:0-47hr acc:winds in grid direction:"x-gradient of log pressure [1/m]
26:6241908:D=2020060306:HGTY:0 m above gnd:kpds=184,105,0:0-47hr acc:winds in grid direction:"y-gradient of height [m/m]
27:6473730:D=2020060306:ICWAT:0 m above gnd:kpds=201,105,0:0-47hr acc:winds in grid direction:"Ice-free water surface [%]
28:6705552:D=2020060306:SHTFL:0 m above gnd:kpds=122,105,0:0-47hr acc:winds in grid direction:"Sensible heat flux [W/m^2]
29:6937374:D=2020060306:ICNG:atmos col:kpds=186,200,0:47hr fcst:winds in grid direction:"Icing SIGMET/AIRMET [non-dim]
30:7223820:D=2020060306:ICWAT:atmos col:kpds=201,200,0:47hr fcst:winds in grid direction:"Ice-free water surface [%]
31:7571242:D=2020060306:UGRD:50 m above gnd:kpds=33,105,50:47hr fcst:winds in grid direction:"u wind [m/s]
32:7803064:D=2020060306:VGRD:50 m above gnd:kpds=34,105,50:47hr fcst:winds in grid direction:"v wind [m/s]
33:8034886:D=2020060306:UGRD:100 m above gnd:kpds=33,105,100:47hr fcst:winds in grid direction:"u wind [m/s]
34:8266708:D=2020060306:VGRD:100 m above gnd:kpds=34,105,100:47hr fcst:winds in grid direction:"v wind [m/s]
35:8498530:D=2020060306:UGRD:200 m above gnd:kpds=33,105,200:47hr fcst:winds in grid direction:"u wind [m/s]
36:8730352:D=2020060306:VGRD:200 m above gnd:kpds=34,105,200:47hr fcst:winds in grid direction:"v wind [m/s]
37:8962174:D=2020060306:UGRD:300 m above gnd:kpds=33,105,300:47hr fcst:winds in grid direction:"u wind [m/s]
38:9193996:D=2020060306:VGRD:300 m above gnd:kpds=34,105,300:47hr fcst:winds in grid direction:"v wind [m/s]
39:9425818:D=2020060306:TMP:925 mb:kpds=11,100,925:47hr fcst:winds in grid direction:"Temp. [K]
40:9773240:D=2020060306:TMP:850 mb:kpds=11,100,850:47hr fcst:winds in grid direction:"Temp. [K]
41:10120662:D=2020060306:TMP:500 mb:kpds=11,100,500:47hr fcst:winds in grid direction:"Temp. [K]
42:10468084:D=2020060306:TMP:300 mb:kpds=11,100,300:47hr fcst:winds in grid direction:"Temp. [K]
43:10815506:D=2020060306:RH:925 mb:kpds=52,100,925:47hr fcst:winds in grid direction:"Relative humidity [%]
44:11162928:D=2020060306:RH:850 mb:kpds=52,100,850:47hr fcst:winds in grid direction:"Relative humidity [%]
45:11510350:D=2020060306:RH:500 mb:kpds=52,100,500:47hr fcst:winds in grid direction:"Relative humidity [%]
46:11857772:D=2020060306:RH:300 mb:kpds=52,100,300:47hr fcst:winds in grid direction:"Relative humidity [%]
47:12205194:D=2020060306:UGRD:925 mb:kpds=33,100,925:47hr fcst:winds in grid direction:"u wind [m/s]
48:12552616:D=2020060306:UGRD:850 mb:kpds=33,100,850:47hr fcst:winds in grid direction:"u wind [m/s]
49:12900038:D=2020060306:UGRD:500 mb:kpds=33,100,500:47hr fcst:winds in grid direction:"u wind [m/s]
50:13247460:D=2020060306:UGRD:300 mb:kpds=33,100,300:47hr fcst:winds in grid direction:"u wind [m/s]
51:13594882:D=2020060306:VGRD:925 mb:kpds=34,100,925:47hr fcst:winds in grid direction:"v wind [m/s]
52:13942304:D=2020060306:VGRD:850 mb:kpds=34,100,850:47hr fcst:winds in grid direction:"v wind [m/s]
53:14289726:D=2020060306:VGRD:500 mb:kpds=34,100,500:47hr fcst:winds in grid direction:"v wind [m/s]
54:14637148:D=2020060306:VGRD:300 mb:kpds=34,100,300:47hr fcst:winds in grid direction:"v wind [m/s]
55:14984570:D=2020060306:GP:925 mb:kpds=6,100,925:47hr fcst:winds in grid direction:"Geopotential [m^2/s^2]
56:15331992:D=2020060306:GP:850 mb:kpds=6,100,850:47hr fcst:winds in grid direction:"Geopotential [m^2/s^2]
57:15679414:D=2020060306:GP:500 mb:kpds=6,100,500:47hr fcst:winds in grid direction:"Geopotential [m^2/s^2]
58:16026836:D=2020060306:GP:300 mb:kpds=6,100,300:47hr fcst:winds in grid direction:"Geopotential [m^2/s^2]
```

**Comment by shahramn** [comment]
The files in that tar file all use non-standard i.e. LOCAL codes in GRIB edition 1.
For example the file HA40_N55_202006290600_03900_GB has table2Version=253 for most of its messages. Only message number 21 uses standard WMO parameter codes i.e. table2Version=1, indicatorOfParameter=66 which is "Snow depth".
wgrib recognizes local NCEP codes but ecCodes does not.
Please note:
According to the WMO, the use of local tables in messages intended for non-local or international exchange is strongly discouraged.

**Comment by meteoDaniel** [comment]
@shahramn thanks for your first introduction to the problem. A description is available under http://projects.knmi.nl/datacentrum/catalogus/catalogus/content/nl-nwp-harm40-grid-p3.html But how can I use this with cfgrib (eccodes)?

**Comment by meteoDaniel** [comment]
@alexamici and @shahramn is it possible to filter by `indicatorOfParameter`? 
A guy from KNMI said that this is the suitable way to read data with eccodes. So i think this ability should be availble in cfgrib , too?

**Comment by iainrussell** [comment]
@meteoDaniel , could you try using `paramId` in the filter, e.g. `backend_kwargs={'filter_by_keys': {'paramId': 131}}`

**Comment by meteoDaniel** [comment]
@iainrussell I am receiving a
```
KeyError: 'paramId'
```
by doing this: 
```
data = xarray.open_dataset('HA40_N55_202006030600_04400_GB', engine='cfgrib', backend_kwargs={'filter_by_keys':{'paramId': 111}})
```

**Comment by iainrussell** [comment]
@meteoDaniel, ah, this goes deep into ecCodes and probably requires the local tables - my mistake.

**Comment by meteoDaniel** [comment]
@iainrussell do you know a guide for me to implement local tables? Actually I only implemented local tables for bufr decoding and not for grib decoding.

**Comment by iainrussell** [comment]
Hi @meteoDaniel , I think this is the page to look at:
https://confluence.ecmwf.int/display/UDOC/Creating+your+own+local+definitions+-+ecCodes+GRIB+FAQ

**Comment by meteoDaniel** [comment]
@iainrussell thanks for the link I have seen this page several times but this is not a good guide. It does not tells me anything about what has to be defined there and why? And no words about the syntax. I have seen some tables with for loops and if clauses. This looks more like a programming language to me than defintions files.

**Comment by meteoDaniel** [comment]
KNMI sent me the corresponding tables right now. 
Now I think I have to create a `/usr/local/share/eccodes/definitions/grib1/local.99.1.def`
that points to the tables?

[HARMONIE_grib1_tables.zip](https://github.com/ecmwf/cfgrib/files/4884193/HARMONIE_grib1_tables.zip)

**Comment by iainrussell** [comment]
Hi @meteoDaniel - that's great news! You can put the tables anywhere you like, you just need to set the environment variable ECCODES_DEFINITION_PATH to point to the 'definitions' directory, e.g.
`export ECCODES_DEFINITION_PATH=/home/me/knmi/definitions`

**Comment by meteoDaniel** [comment]
@iainrussell  But there are defintions missing? Or do you were able to open data by just adding the tables to the DEFINITION_PATH?

**Comment by shahramn** [comment]
I tried your tables and it seems to work fine.
% ls /tmp/Downloads/knmi_def/definitions
grib1  grib2
% export ECCODES_DEFINITION_PATH=/tmp/Downloads/knmi_def/definitions
% grib_ls -n parameter HARM_40_v1_p3_06/HA40_N55_202006290600_00000_GB
centre      paramId     units       name        shortName   
99          99253001    Pa          Pressure    pres       
99          99253011    K           Temperature  t          
99          99253052    (0-1)       Relative humidity  r          
99          99253017    K           Dew point temperature  td         
...

**Comment by meteoDaniel** [comment]
Okay, I am receiving
```
In [2]: data = cfgrib.open_datasets('HA40_N55_202006030600_04400_GB')                                                                                                        
Ignoring index file '/home/d.lassahn/Schreibtisch/cfgrib_test/HA40_N55_202006030600_04400_GB.4cc40.idx' incompatible with GRIB file
ECCODES ERROR   :  Unable to find boot.def. Context path=/home/d.lassahn/Downloads/knmi_def/definitions

Possible causes:
- The software is not correctly installed
- The environment variable ECCODES_DEFINITION_PATH is defined but incorrect

ecCodes assertion failed: `0' in /build/eccodes-VmTPeV/eccodes-2.6.0/src/grib_context.c:205
```

**Comment by iainrussell** [comment]
Almost there!  I think you need to add the original path to the installed definitions. If they are in /usr/local/share/eccodes/definitions then you need this:
`export ECCODES_DEFINITION_PATH=/home/d.lassahn/Downloads/knmi_def/definitions:/usr/local/share/eccodes/definitions`

**Comment by shahramn** [comment]
You are using a much older ecCodes version it seems (v2.6.0)
In the older versions you have to include the standard location of definitions as well.
For example if you installed ecCodes in /usr/local/eccodes, then the default location will be
/usr/local/eccodes/share/eccodes/definitions

So the environment variable would have to include this as well as your overridden location
export ECCODES_DEFINITION_PATH=/tmp/Downloads/knmi_def/definitions:/usr/local/eccodes/share/eccodes/definitions

**Comment by meteoDaniel** [comment]
Thanks guys for your support ! It works fine for me now.

**Comment by ddotabma** [comment]
@meteoDaniel Thanks for bringing up this topic. I am running into the same issue, and reading that you have the solution it would be great for me (and probably others) if you can share a minimal working example that solves the problem?
