### ISSUE TITLE
What to do if additional grib tables not used?

### ISSUE THREAD

**Issue by meteoDaniel** [ecmwf/cfgrib#177]
Dear cfgrib community, 
I am having a strange situation. 
I build a docker image with `cfgrib`,`xarray `and `libeccodes0` with `python:3.7.7-slim` as base image and defined an additonal  `ECCODES_DEFINITION_PATH`. This worked fine. 
But doing the same on another machine with some additonal configurations which should not affect `cfgrib` and `eccodes` it does not work. The grib tables were not recognized. 

So how can I debug this issue?
Is there a way to force cfgrib/xarray to use the grib tables via python script (not via `ECCODES_DEFINTION_PATH`) ?

Thanks a lot for support.

**Comment by alexamici** [comment]
This specific problem looks more of an issue for *eccodes*, as *cfgrib* doesn't read or use the `ECCODES_DEFINITION_PATH` environment variable.

If you have the chance to do it, installing from *conda* protects from a lot of system problem.

**Comment by meteoDaniel** [comment]
Okay 5 minutes ago I have found the solution. 
The postfix has to be specified according to the grib tables directory. In my case after extracting a `tar` archive I have stored the grib files with `.grib` instead of `.grib1`

Nevertheless thanks a lot @alexamici
