### ISSUE TITLE
How to access PV coefficients to build pressure levels from model level GRIB file

### ISSUE THREAD

**Issue by jdassink** [ecmwf/cfgrib#178]
Hello!

I would like to be able to convert model levels to pressure levels (and from there to altitude).
Is it possible to access the pv coefficients when I read in a GRIB file as an Xarray using cfgrib? 

I know it is possible to store the PV coefficients in Python code, but I would prefer to be able to read them from the GRIB files, so I don't have to store PV coefficients for different model types.

Thanks,
Jelle

**Comment by alexamici** [comment]
@jdassink this looks more like a question than an issue, so I'd advise you to ask on StackOverflow where more people may be seeing the question.

If you know the key names for the parameter I think you may use the `read_keys` to access them.

**Comment by jdassink** [comment]
Looks like this does about the trick

```
ds = []
list_keys = ['pv']

for shortName in ['z', 'lnsp', 't', 'q', 'u', 'v', 'w']:
    print('Reading parameter {}'.format(shortName))
    ds += [ xr.open_dataset(fid_grib,
                          engine='cfgrib',
                          backend_kwargs={'read_keys': list_keys,
                                          'filter_by_keys': 
                                              {'typeOfLevel': 'hybrid',
                                               'shortName': shortName}})]
ds = xr.merge(ds)
pv_coeff = np.array(ds.t.GRIB_pv)
pv_coeff.shape
```

Thanks for pointing me to the read_keys() suggestion.
