### ISSUE TITLE
open_datasets does not read all fields in HRRR GRIBv2 file

### ISSUE THREAD

**Issue by DanielAdriaansen** [ecmwf/cfgrib#192]
I am working with a High Resolution Rapid Refresh (HRRR) file from NOAA. These files have a level type of 'hybrid' in them (among others), and wgrib2 tells me there are 20 fields with this level type:

```
1:0:vt=2021010615:PRES:1 hybrid level:3 hour fcst:
2:2249626:vt=2021010615:CLMR:1 hybrid level:3 hour fcst:
3:2311584:vt=2021010615:CIMIXR:1 hybrid level:3 hour fcst:
4:2324108:vt=2021010615:RWMR:1 hybrid level:3 hour fcst:
5:2652499:vt=2021010615:SNMR:1 hybrid level:3 hour fcst:
6:2684324:vt=2021010615:GRLE:1 hybrid level:3 hour fcst:
7:2715761:vt=2021010615:NCONCD:1 hybrid level:3 hour fcst:
8:2804569:vt=2021010615:NCCICE:1 hybrid level:3 hour fcst:
9:2812538:vt=2021010615:SPNCR:1 hybrid level:3 hour fcst:
10:3179350:vt=2021010615:PMTF:1 hybrid level:3 hour fcst:
11:3877885:vt=2021010615:PMTC:1 hybrid level:3 hour fcst:
12:4211430:vt=2021010615:FRACCC:1 hybrid level:3 hour fcst:
13:4388347:vt=2021010615:HGT:1 hybrid level:3 hour fcst:
14:6693595:vt=2021010615:TMP:1 hybrid level:3 hour fcst:
15:7865973:vt=2021010615:SPFH:1 hybrid level:3 hour fcst:
16:9188224:vt=2021010615:UGRD:1 hybrid level:3 hour fcst:
17:10446108:vt=2021010615:VGRD:1 hybrid level:3 hour fcst:
18:11702177:vt=2021010615:VVEL:1 hybrid level:3 hour fcst:
19:13013262:vt=2021010615:TKE:1 hybrid level:3 hour fcst:
20:13640064:vt=2021010615:MASSDEN:1 hybrid level:3 hour fcst:
```

When I open this file with cfgrib like this:

`cfgrib.open_datasets(filename)`

I receive this info:
```
<xarray.Dataset>
Dimensions:     (hybrid: 50, x: 1799, y: 1059)
Coordinates:
    time        datetime64[ns] 2021-01-06T12:00:00
    step        timedelta64[ns] 03:00:00
  * hybrid      (hybrid) int64 1 2 3 4 5 6 7 8 9 ... 42 43 44 45 46 47 48 49 50
    latitude    (y, x) float64 21.14 21.15 21.15 21.16 ... 47.86 47.85 47.84
    longitude   (y, x) float64 237.3 237.3 237.3 237.4 ... 299.0 299.0 299.1
    valid_time  datetime64[ns] 2021-01-06T15:00:00
Dimensions without coordinates: x, y
Data variables:
    paramId_0   (hybrid, y, x) float32 ...
    pres        (hybrid, y, x) float32 ...
    t           (hybrid, y, x) float32 ...
    u           (hybrid, y, x) float32 ...
    v           (hybrid, y, x) float32 ...
    q           (hybrid, y, x) float32 ...
    w           (hybrid, y, x) float32 ...
    gh          (hybrid, y, x) float32 ...
    cc          (hybrid, y, x) float32 ...
    clwmr       (hybrid, y, x) float32 ...
    rwmr        (hybrid, y, x) float32 ...
    snmr        (hybrid, y, x) float32 ...
    grle        (hybrid, y, x) float32 ...
    tke         (hybrid, y, x) float32 ...
    pmtc        (hybrid, y, x) float32 ...
    pmtf        (hybrid, y, x) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP 
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP ,
```
Note there are only 16 fields (actually 15 if you discount "paramid_0") and not 20. I am missing:
```
3:2311584:vt=2021010615:CIMIXR:1 hybrid level:3 hour fcst:
7:2715761:vt=2021010615:NCONCD:1 hybrid level:3 hour fcst:
8:2804569:vt=2021010615:NCCICE:1 hybrid level:3 hour fcst:
9:2812538:vt=2021010615:SPNCR:1 hybrid level:3 hour fcst:
20:13640064:vt=2021010615:MASSDEN:1 hybrid level:3 hour fcst:
```
Are these fields being overwritten as paramid_0? If so, is there a way to use the raw variable name info (i.e. discipline mastertab localtab center parmcat parmnum) to distinguish these from one another?

I can provide a sample file via the web if needed, or you can obtain one in realtime via this link:
https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/

Thank you!

**Comment by DanielAdriaansen** [comment]
I am using Xarray, and I will try using backend_kwargs and passing the paramId for each of the missing vars to see if I can find them and report back.

**Comment by DanielAdriaansen** [comment]
> I am using Xarray, and I will try using backend_kwargs and passing the paramId for each of the missing vars to see if I can find them and report back.

This was unsuccessful. Some more interrogation of the GRIB file using:
`grib_get -p shortName filename.grb2`

reveals the shortNames for all of these fields are "unknown".

Printing the paramId via:
`grib_get -p paramId filename.grb2`

reveals indeed that all of them have a paramId of 0.

Perhaps there is a way to edit the GRIB file to somehow make these unique enough that cfgrib could read them? Looking in dataset.py, I think the only keys I can use to try and pull them out are listed in `DATA_ATTRIBUTES_KEYS` and `EXTRA_DATA_ATTRIBUTES_KEYS` is that correct?

**Comment by shahramn** [comment]
The NOAA GRIB2 files are using LOCAL encodings of parameters which are not standard WMO codings. These have local tables which wgrib2 knows about but not ecCodes.

**Comment by DanielAdriaansen** [comment]
Thanks @shahramn. Sounds like a garbage in, garbage out issue and perhaps not solvable via cfgrib. I am going to close this for now.
