### ISSUE TITLE
Get "raw" typeOfLevel in addition to the one translated via eccodes

### ISSUE THREAD

**Issue by maxhollmann** [ecmwf/cfgrib#194]
The issue I have is that some level types from GFS grib2 files end up as `unknown` in `GRIB_typeOfLevel`. Is it possible to get at the underlying id or whatever it is that eccodes translates into the `typeOfLevel`?

I'm almost certain I've seen an option to disable translation of some attributes somewhere, but can't find it anymore. Is this possible?

**Comment by shahramn** [comment]
ecCodes computes the "typeOfLevel" key from two underlying coded keys:
typeOfFirstFixedSurface
typeOfSecondFixedSurface

See https://github.com/ecmwf/eccodes/blob/develop/definitions/grib2/typeOfLevelConcept.def

**Comment by maxhollmann** [comment]
That's it. Thank you so much :)
