### ISSUE TITLE
open_datasets does not work with filter_by_keys argument

### ISSUE THREAD

**Issue by Eric-Lee** [ecmwf/cfgrib#196]
I am trying to use the `filter_by_keys` argument with `open_datasets` like this:

```python
 cfgrib.open_datasets('gdas.grb2', backend_kwargs={'filter_by_keys': {'typeOfLevel': 'isobaricInhPa'}})
```

However, I get the error `TypeError: open_fileindex() got an unexpected keyword argument 'filter_by_keys'`
It seems that the `open_fileindex` function was refactored at some point but the `open_datasets` functionality was never updated in turn.

I fixed the issue by updating the function `open_variable_datasets` in `xarray_store.py` as follows:

```python
def open_variable_datasets(path, backend_kwargs={}, **kwargs):
    fileindex_kwargs = {
        key: backend_kwargs[key]
        for key in ['indexpath', 'grib_errors']
        if key in backend_kwargs
    }

    index = open_fileindex(path, **fileindex_kwargs).subindex(backend_kwargs.get('filter_by_keys', {}))
    
    datasets = []
    for param_id in sorted(index['paramId']):
        bk = backend_kwargs.copy()
        bk['filter_by_keys'] = backend_kwargs.get('filter_by_keys', {}).copy()
        bk['filter_by_keys']['paramId'] = param_id
        datasets.extend(raw_open_datasets(path, bk, **kwargs))
    return datasets
```
Edit: original posted solution failed when `'filter_by_keys'` was not present.

**Comment by alexamici** [comment]
@Eric-Lee d'oh! You are right, I'll fix the bug in a different way, but your fix looks correct.

Thanks!
