### ISSUE TITLE
too many indices for array

### ISSUE THREAD

**Issue by hilma91** [ecmwf/cfgrib#199]
I downloaded a seasonal forecast grib file from the ecmwf website. I am trying to to convert a grib file into a csv file and this is my script to read the grib file:
def seasonal_forecast():
    d = 'C:/Users/Hilma/Master_Thesis/rodis_data/rodis/obere_dhuenn/timeseries/'
    grib_filename = os.path.join(d, 'seasonal_forecast/c3s/obere_dhuenn_seasonal_forecast.grib')

    ds = xr.open_dataset(grib_filename, engine="cfgrib",
                         backend_kwargs=dict(filter_by_keys={'typeOfLevel': 'surface', 'dataType': 'hcmean'}))
    for v in ds:
        print("{}, {}, {}".format(v, ds[v].attrs["long_name"], ds[v].attrs["units"]))

Can someone please help me to solve the error below: 

C:\Users\Hilma\Anaconda3\python.exe C:/Users/Hilma/Master_Thesis/caeli-master/caeli/pdsi.py
Ignoring index file 'C:\\Users\\Hilma\\Master_Thesis\\rodis_data\\rodis\\obere_dhuenn\\timeseries\\seasonal_forecast\\c3s\\obere_dhuenn_seasonal_forecast.grib.90c91.idx' incompatible with GRIB file
Traceback (most recent call last):
  File "C:/Users/Hilma/Master_Thesis/caeli-master/caeli/pdsi.py", line 135, in <module>
    seasonal_forecast()
  File "C:/Users/Hilma/Master_Thesis/caeli-master/caeli/pdsi.py", line 127, in seasonal_forecast
    backend_kwargs=dict(filter_by_keys={'typeOfLevel': 'surface', 'dataType': 'hcmean'}))
  File "C:\Users\Hilma\Anaconda3\lib\site-packages\xarray\backends\api.py", line 527, in open_dataset
    filename_or_obj, lock=lock, **backend_kwargs
  File "C:\Users\Hilma\Anaconda3\lib\site-packages\xarray\backends\cfgrib_.py", line 43, in __init__
    self.ds = cfgrib.open_file(filename, **backend_kwargs)
  File "C:\Users\Hilma\Anaconda3\lib\site-packages\cfgrib\dataset.py", line 651, in open_file
    return Dataset(*build_dataset_components(index, read_keys=read_keys, **kwargs))
  File "C:\Users\Hilma\Anaconda3\lib\site-packages\cfgrib\dataset.py", line 583, in build_dataset_components
    time_dims=time_dims,
  File "C:\Users\Hilma\Anaconda3\lib\site-packages\cfgrib\dataset.py", line 494, in build_variable_components
    geo_dims, geo_shape, geo_coord_vars = build_geography_coordinates(index, encode_cf, errors)
  File "C:\Users\Hilma\Anaconda3\lib\site-packages\cfgrib\dataset.py", line 379, in build_geography_coordinates
    if latitudes[0] > latitudes[-1]:
IndexError: too many indices for array
Process finished with exit code 1

**Comment by iainrussell** [comment]
Hi, it looks like something strange with the index file. Could you disable indexing as described here: https://github.com/ecmwf/cfgrib#grib-index-file  - and you may need to remove the file obere_dhuenn_seasonal_forecast.grib.90c91.idx too.

**Comment by hilma91** [comment]
I am still getting "IndexError: too many indices for array"

**Comment by iainrussell** [comment]
Hello @hilma91 - could you attach the GRIB file to this issue if it's not too large please? Perhaps just the first message in the file would be enough. Thanks.

**Comment by hilma91** [comment]
[obere_dhuenn_seasonal_forecast.zip](https://github.com/ecmwf/cfgrib/files/6018101/obere_dhuenn_seasonal_forecast.zip)

Kindly see attached

**Comment by iainrussell** [comment]
Hello @hilma91 , many thanks for this. If you're in a position to use the latest version in the master branch from github, then you should find that this data now loads with cfgrib! The problem was that these GRIB messages each contained only a single grid point, and there was some code in cfgrib that assumed that we would always have more than one point.
