### ISSUE TITLE
Add support for saving the index produced with a full GIRB scan at open.

### ISSUE THREAD

**Issue by alexamici** [ecmwf/cfgrib#20]
At the moment every time a GRIB file is opened *cfgrib* needs to scan all the messages in the file to build the index that is then used to compute the values of the coordinates and build the hypercube representation of the variables.

Worse, when opening a GRIB file with the convenience function `open_datasets` the index is discarded every time the recursive call fails and the expensive file scan is done again.

Proposed implementation requirements for the feature are:
 - [x] save the index to disk with `path` + `.idx` immediately after computation
   - a pickle of the in-memory structure is the simplest implementation
   - shall not fail if the index cannot be written (file can be on a read only filesystem)
 - [x] when opening a file search for the `path` + `.idx` index file, test that it is in sync with the GRIB file and load it
   - timestamp ordering is enough for now
   - do not fail if the index is corrupt
 - [ ] use locking to avoid concurrent writes or reads and write
   - concurrents reads must be ok

**Comment by iainrussell** [comment]
I think it's worth mentioning that it probably should not fail if it cannot write the index file - the GRIB file could be in a read-only directory, in which case it would not be possible to write the index to the same place.

**Comment by alexamici** [comment]
The implementation is still wasteful and very fragile, but the index is save to and read from disk.

**Comment by ejhyer** [comment]
I just want to bump @iainrussell point above-- at present, it does not fail when reading from a read-only directory, but it produces a message spew that certainly resembles an I/O error. Versions:
cfgrib                    0.9.9.1            pyhd8ed1ab_1    conda-forge
eccodes                   2.23.0               h7621a5c_0    conda-forge
python-eccodes            2021.03.0        py39hce5d2b2_2    conda-forge
xarray                    0.18.2             pyhd8ed1ab_0    conda-forge
