### ISSUE TITLE
How to filter over Coordinates? Problem with switch from COSMO-D2 to ICON-D2

### ISSUE THREAD

**Issue by ttjaden** [ecmwf/cfgrib#202]
**I made a small notebook to show our problem**

```python
import xarray as xr
import pandas as pd
```

```python
# Until a few weeks ago we processed COSMO-D2 (irradiation) like this
file1 = 'cosmo-d2_germany_regular-lat-lon_single-level_2020031900_009_ASWDIFD_S.grib2'
ds1 = xr.open_dataset(file1, engine="cfgrib", backend_kwargs={'filter_by_keys': {'stepUnits': 1}})
ds1
# the 'backend_kwargs={'filter_by_keys': {'stepUnits': 1}}' was neccessary to get the data from full hours
```

<pre>&lt;xarray.Dataset&gt;
Dimensions:     (latitude: 701, longitude: 851)
Coordinates:
    time        datetime64[ns] ...
    step        timedelta64[ns] ...
    surface     int64 ...
  * latitude    (latitude) float64 43.0 43.02 43.04 43.06 ... 56.96 56.98 57.0
  * longitude   (longitude) float64 0.0 0.02 0.04 0.06 ... 16.96 16.98 17.0
    valid_time  datetime64[ns] ...
Data variables:
    ASWDIFD_S   (latitude, longitude) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             edzw
    GRIB_centreDescription:  Offenbach 
    GRIB_subCentre:          255
    Conventions:             CF-1.7
    institution:             Offenbach 
    history:                 2021-02-17T23:43:06 GRIB to CDM+CF via cfgrib-0....</pre>

```python
# As a dataframe all was fine
df1 = ds1.to_dataframe()
df1
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>time</th>
      <th>step</th>
      <th>surface</th>
      <th>valid_time</th>
      <th>ASWDIFD_S</th>
    </tr>
    <tr>
      <th>latitude</th>
      <th>longitude</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="5" valign="top">43.0</th>
      <th>0.00</th>
      <td>2020-03-19</td>
      <td>09:00:00</td>
      <td>0</td>
      <td>2020-03-19 09:00:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>0.02</th>
      <td>2020-03-19</td>
      <td>09:00:00</td>
      <td>0</td>
      <td>2020-03-19 09:00:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>0.04</th>
      <td>2020-03-19</td>
      <td>09:00:00</td>
      <td>0</td>
      <td>2020-03-19 09:00:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>0.06</th>
      <td>2020-03-19</td>
      <td>09:00:00</td>
      <td>0</td>
      <td>2020-03-19 09:00:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>0.08</th>
      <td>2020-03-19</td>
      <td>09:00:00</td>
      <td>0</td>
      <td>2020-03-19 09:00:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>...</th>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th rowspan="5" valign="top">57.0</th>
      <th>16.92</th>
      <td>2020-03-19</td>
      <td>09:00:00</td>
      <td>0</td>
      <td>2020-03-19 09:00:00</td>
      <td>30.479958</td>
    </tr>
    <tr>
      <th>16.94</th>
      <td>2020-03-19</td>
      <td>09:00:00</td>
      <td>0</td>
      <td>2020-03-19 09:00:00</td>
      <td>30.479958</td>
    </tr>
    <tr>
      <th>16.96</th>
      <td>2020-03-19</td>
      <td>09:00:00</td>
      <td>0</td>
      <td>2020-03-19 09:00:00</td>
      <td>30.490700</td>
    </tr>
    <tr>
      <th>16.98</th>
      <td>2020-03-19</td>
      <td>09:00:00</td>
      <td>0</td>
      <td>2020-03-19 09:00:00</td>
      <td>30.490700</td>
    </tr>
    <tr>
      <th>17.00</th>
      <td>2020-03-19</td>
      <td>09:00:00</td>
      <td>0</td>
      <td>2020-03-19 09:00:00</td>
      <td>30.483864</td>
    </tr>
  </tbody>
</table>
<p>596551 rows × 5 columns</p>
</div>

```python
# Now we switched to ICON-D2 with a problem
file2 = 'icon-d2_germany_regular-lat-lon_single-level_2021021700_000_2d_aswdifd_s.grib2'
# The filter is not working anymore 'backend_kwargs={'filter_by_keys': {'stepUnits': 1}}'
# Therefore read without filter
ds2 = xr.open_dataset(file2, engine="cfgrib")
ds2
# Unfortunately 'step' ist in the coordinates/index
```

<pre>&lt;xarray.Dataset&gt;
Dimensions:     (latitude: 746, longitude: 1215, step: 4)
Coordinates:
    time        datetime64[ns] ...
  * step        (step) timedelta64[ns] 00:00:00 00:15:00 00:30:00 00:45:00
    surface     int64 ...
  * latitude    (latitude) float64 43.18 43.2 43.22 43.24 ... 58.04 58.06 58.08
  * longitude   (longitude) float64 -3.94 -3.92 -3.9 -3.88 ... 20.3 20.32 20.34
    valid_time  (step) datetime64[ns] ...
Data variables:
    ASWDIFD_S   (step, latitude, longitude) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             edzw
    GRIB_centreDescription:  Offenbach 
    GRIB_subCentre:          255
    Conventions:             CF-1.7
    institution:             Offenbach 
    history:                 2021-02-17T23:43:09 GRIB to CDM+CF via cfgrib-0....</pre>

```python
# As a dataframe it looks like this
df2 = ds2.to_dataframe()
df2
# unfortunately 'step' is in the index
# unfortunately there are 'step' values for non-full hours
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th></th>
      <th>time</th>
      <th>surface</th>
      <th>valid_time</th>
      <th>ASWDIFD_S</th>
    </tr>
    <tr>
      <th>latitude</th>
      <th>longitude</th>
      <th>step</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="5" valign="top">43.18</th>
      <th rowspan="4" valign="top">-3.94</th>
      <th>00:00:00</th>
      <td>2021-02-17</td>
      <td>0</td>
      <td>2021-02-17 00:00:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>00:15:00</th>
      <td>2021-02-17</td>
      <td>0</td>
      <td>2021-02-17 00:15:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>00:30:00</th>
      <td>2021-02-17</td>
      <td>0</td>
      <td>2021-02-17 00:30:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>00:45:00</th>
      <td>2021-02-17</td>
      <td>0</td>
      <td>2021-02-17 00:45:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>-3.92</th>
      <th>00:00:00</th>
      <td>2021-02-17</td>
      <td>0</td>
      <td>2021-02-17 00:00:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>...</th>
      <th>...</th>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th rowspan="5" valign="top">58.08</th>
      <th>20.32</th>
      <th>00:45:00</th>
      <td>2021-02-17</td>
      <td>0</td>
      <td>2021-02-17 00:45:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th rowspan="4" valign="top">20.34</th>
      <th>00:00:00</th>
      <td>2021-02-17</td>
      <td>0</td>
      <td>2021-02-17 00:00:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>00:15:00</th>
      <td>2021-02-17</td>
      <td>0</td>
      <td>2021-02-17 00:15:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>00:30:00</th>
      <td>2021-02-17</td>
      <td>0</td>
      <td>2021-02-17 00:30:00</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>00:45:00</th>
      <td>2021-02-17</td>
      <td>0</td>
      <td>2021-02-17 00:45:00</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>3625560 rows × 4 columns</p>
</div>

```python

```

**Question: What to do?**

**Comment by iainrussell** [comment]
Hello @ttjaden , it's not completely clear to me what you want here - do you want to select just one forecast step? If so, it should be possible via `backend_kwargs={'filter_by_keys': {'step': 0}}` for example. Otherwise, the step is a dimension of the data as far as I can see, and I'm not sure you can eliminate it other than filtering just one step. If you don't have a list of available keys in the file, you can use tools such as eccodes, codesUI or Metview to inspect the file. Sorry if this is not much help!

**Comment by ttjaden** [comment]
Thanks for the hint! This worked!
