### ISSUE TITLE
`KeyError: 1508328000000000000` write support broken with pandas 1.1+

### ISSUE THREAD

**Issue by alexamici** [ecmwf/cfgrib#222]
Looks like the already flaky write support was completely broken by an incompatibility between *xarray* and newer versions of *pandas*.

A work-around is to downgrade *pandas* to the latest 1.0.x version `conda install -c conda-forge pandas=1.0.5` or `pip install pandas=1.0.5`.

**Comment by honnorat** [comment]
Yes, this is the same as #156

**Comment by alexamici** [comment]
You are right! Closing as duplicate.
