### ISSUE TITLE
Release 0.9.9.0

### ISSUE THREAD

**Issue by alexamici** [ecmwf/cfgrib#224]
I already did most of the release tasks, but let's keep the checklist as a reminder:
- [x] check all tests are `passed` or `xfailed` and there are no unexplained `xpassed`, `skipped` or `warning` 
- [x] check issues and sync MANIFEST, CHANGELOG and README
- [x] prepare announcement
- [x] sync release branch `stable/0.9.9.x` with `master`
- [x] run `fullrelease` on release branch (includes upload to PyPI)
- [x] sync `master` with release branch
- [x] test PyPI package
- [x] update cfgrib-feedstock (accept the automatic PR) and test the conda package 
- [x] announce release

cc @iainrussell and @aurghs

**Comment by alexamici** [comment]
@iainrussell going for the release now

**Comment by alexamici** [comment]
Release on PyPI, testing now.

**Comment by alexamici** [comment]
I tested the PyPI package both with current and future *xarray*.

Translating a 130.000 message GRIB file to netCDF went from "no one ever waited long enough to know" to about 2:30 minutes 😆

**Comment by iainrussell** [comment]
That's fantastic, I'm sure it will be much appreciated!

**Comment by alexamici** [comment]
OK, I plan to announce the release on twitter early in the afternoon.
