### ISSUE TITLE
Metadata inconsistency betweene cfgrib/xarray and pygrib

### ISSUE THREAD

**Issue by winash12** [ecmwf/cfgrib#229]
I am not sure if it's a cfgrib issue or xarray issue but I will start off here and then move it to xarray if it's not a cfgrib issue.

I am trying to read one of these files - https://nomads.ncep.noaa.gov/pub/data/nccf/com/cfs/prod/cfs/cfs.20210426/00/6hrly_grib_01/ - let's assume I want to read this file -                                    -   
flxf2021042600.01.2021042600.grb2  and this is the code I have

`
import xarray as xr

ds = xr.open_dataset('./flxf2021042600.01.2021042600.grb2',engine='cfgrib',backend_kwargs={'errors': 'ignore','filter_by_keys': {'typeOfLevel': 'heightAboveGround'}})`

When I print out the value of ds I encounter two issues 

1) I am looking for these three variables - UGRD:10 m above ground:anl:, VGRD:10 m above ground:anl: and TMP:2 m above ground:anl: as indicated in the indx file - https://nomads.ncep.noaa.gov/pub/data/nccf/com/cfs/prod/cfs/cfs.20210426/00/6hrly_grib_01/flxf2021042600.01.2021042600.grb2.idx

I only obtain what it appears to be ugrd and vgrd. Even here it prints out it as u10 and v10. Are u10 and v10 the same as UGRD and VGRD ?

2) I am unable to obtain TMP completely. When I try to do the same with pygrib I obtain all 3 completely.

Where am I going wrong ?

**Comment by shahramn** [comment]
Using the ecCodes tools we can see that there are 99 messages in this file but some of them are multi-field i.e., one GRIB message has several fields.
% grib_count flxf2021042600.01.2021042600.grb2
99
% grib_ls flxf2021042600.01.2021042600.grb2
...
101 of 101 messages in flxf2021042600.01.2021042600.grb2

Now regarding the naming of the parameters: wgrib2 uses a different naming convention from ecCodes. But we can put the two listings side by side to see the correspondence.
Eg.
% grib_ls -p count,shortName  flxf2021042600.01.2021042600.grb2
...
36          10u        
37          10v        
38          2t         
...
And now wgrib2
% wgrib2 flxf2021042600.01.2021042600.grb2
...
36.1:1903113:d=2021042600:UGRD:10 m above ground:anl:
36.2:1903113:d=2021042600:VGRD:10 m above ground:anl:
37:2031712:d=2021042600:TMP:2 m above ground:anl:
...

The message numbers do not match exactly because of the multi-field aspect I mentioned before. But otherwise they are the same; so what wgrib2 calls UGRD is what ecCodes calls 10u etc

**Comment by winash12** [comment]
@shahramn Thanks for the prompt response ! Truly appreciated. I had only final clarification. Using python and eccodes and cfgrib how can I extract the 38 2t variable ? It's not available as part of  heightAboveGround. It's clear that UGRD and VGRD are the same as u10 and v10. Only TMP remains an issue now.

**Comment by winash12** [comment]
@shahramn If I used this piece of code 

`ds = xr.open_dataset('./flxf2021042100.01.2021042100.grb2',engine='cfgrib',backend_kwargs={'errors': 'ignore'})`

I get this output 

`Traceback (most recent call last):
  File "test.py", line 11, in <module>
    ds = xr.open_dataset('./flxf2021042100.01.2021042100.grb2',engine='cfgrib',backend_kwargs={'errors': 'ignore'})
  File "/usr/local/lib/python3.8/dist-packages/xarray/backends/api.py", line 526, in open_dataset
    store = backends.CfGribDataStore(
  File "/usr/local/lib/python3.8/dist-packages/xarray/backends/cfgrib_.py", line 43, in __init__
    self.ds = cfgrib.open_file(filename, **backend_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cfgrib-0.9.8.5-py3.8.egg/cfgrib/dataset.py", line 651, in open_file
  File "/usr/local/lib/python3.8/dist-packages/cfgrib-0.9.8.5-py3.8.egg/cfgrib/dataset.py", line 596, in build_dataset_components
cfgrib.dataset.DatasetBuildError: multiple values for unique key, try re-open the file with one of:
    filter_by_keys={'typeOfLevel': 'surface'}
    filter_by_keys={'typeOfLevel': 'depthBelowLandLayer'}
    filter_by_keys={'typeOfLevel': 'nominalTop'}
    filter_by_keys={'typeOfLevel': 'highCloudLayer'}
    filter_by_keys={'typeOfLevel': 'highCloudTop'}
    filter_by_keys={'typeOfLevel': 'highCloudBottom'}
    filter_by_keys={'typeOfLevel': 'middleCloudLayer'}
    filter_by_keys={'typeOfLevel': 'middleCloudTop'}
    filter_by_keys={'typeOfLevel': 'middleCloudBottom'}
    filter_by_keys={'typeOfLevel': 'lowCloudLayer'}
    filter_by_keys={'typeOfLevel': 'lowCloudTop'}
    filter_by_keys={'typeOfLevel': 'lowCloudBottom'}
    filter_by_keys={'typeOfLevel': 'heightAboveGround'}
    filter_by_keys={'typeOfLevel': 'atmosphereSingleLayer'}
    filter_by_keys={'typeOfLevel': 'convectiveCloudLayer'}
    filter_by_keys={'typeOfLevel': 'boundaryLayerCloudLayer'}
    filter_by_keys={'typeOfLevel': 'hybrid'}
`
so you would think TMP would be contained in heightAboveGround but you can try printing it out and it's not there.

**Comment by shahramn** [comment]
Using the ecCodes tool "grib_copy", one can extract a given GRIB message as follows:
```
% grib_copy -w shortName=2t flxf2021042600.01.2021042600.grb2 2t.grib
% grib_ls -j 2t.grib
    "edition": 2,
    "centre": "kwbc",
    "date": 20210426,
    "dataType": "fc",
    "gridType": "regular_gg",
    "stepRange": 0,
    "typeOfLevel": "heightAboveGround",
    "level": 2,
    "shortName": "2t",
    "packingType": "grid_jpeg"
```

**Comment by winash12** [comment]
`ds = xr.open_dataset('./flxf2021042100.01.2021042100.grb2',engine='cfgrib',backend_kwargs={'errors': 'ignore','filter_by_keys': {'typeOfLevel': 'heightAboveGround'}})

print(ds)`

I am only getting u10 and v10 


`<xarray.Dataset>
Dimensions:            (latitude: 190, longitude: 384)
Coordinates:
    time               datetime64[ns] ...
    step               timedelta64[ns] ...
    heightAboveGround  int64 ...
  * latitude           (latitude) float64 89.28 88.34 87.4 ... -88.34 -89.28
  * longitude          (longitude) float64 0.0 0.9375 1.875 ... 358.1 359.1
    valid_time         datetime64[ns] ...
Data variables:
    u10                (latitude, longitude) float32 ...
    v10                (latitude, longitude) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP 
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP 
    history:                 2021-04-28T19:46:27 GRIB to CDM+CF via cfgrib-0....`

**Comment by alexamici** [comment]
@winash12 *cfgrib* can't access variables at 10m at the same time of variables at 2m. You may filter by short name `'filter_by_keys': {'shortName': 't2m'}}` I think may work.

**Comment by winash12** [comment]
@alexamici Maybe I can't spot the error in this - 

`ds1 = xr.open_dataset('./flxf2021042100.01.2021042100.grb2',engine='cfgrib',backend_kwargs={'errors': 'ignore','filter_by_keys': {'shortName': 't2m'}})`

but I get this error now - 
`
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    ds1 = xr.open_dataset('./flxf2021042100.01.2021042100.grb2',engine='cfgrib',backend_kwargs={'errors': 'ignore','filter_by_keys': {'shortName': 't2m'}})
  File "/usr/local/lib/python3.8/dist-packages/xarray/backends/api.py", line 526, in open_dataset
    store = backends.CfGribDataStore(
  File "/usr/local/lib/python3.8/dist-packages/xarray/backends/cfgrib_.py", line 43, in __init__
    self.ds = cfgrib.open_file(filename, **backend_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cfgrib-0.9.8.5-py3.8.egg/cfgrib/dataset.py", line 651, in open_file
  File "/usr/local/lib/python3.8/dist-packages/cfgrib-0.9.8.5-py3.8.egg/cfgrib/dataset.py", line 573, in build_dataset_components
  File "/usr/local/lib/python3.8/dist-packages/cfgrib-0.9.8.5-py3.8.egg/cfgrib/messages.py", line 391, in __getitem__
KeyError: 'paramId'
`

**Comment by winash12** [comment]
@alexamici I eventually had to go with this  

`ds1 = xr.open_dataset('./flxf2021042100.01.2021042100.grb2',engine='cfgrib',backend_kwargs={'errors': 'ignore','filter_by_keys': {'shortName': '2t'}})`
