### ISSUE TITLE
Dependency nightmare on Windows Server 2012 R2 standard, conda 4.10.3

### ISSUE THREAD

**Issue by alkhwarizmi** [ecmwf/cfgrib#257]
Dear all,

first of all thank you for providing the Python community with this useful package for dealing with grib data. Not sure you can do something about what I am going to say but I think it is something that you should know.

I would like to signal that installing cfgrib on my machines (PCs and also a server) using conda is still a configuration pain.

I was able to install it on my PC relatively easily. Instead, on the server the process failed after several hours with option
`conda config --set channel_priority strict`. I am currently repeating the process (since 08:30) with option `conda config --set channel_priority false` and I don't know if it will be successful, eventually.

Have you an idea of what could be the packages causing this dependency nightmare? Is is possible that there are so many dependencies for a relatively low-level package, which in turn is relying on an external dll for doing the job? I would recommend reducing them to a minimum set of very stable packages to ease installation problems of this useful package. 

Sincerely,

**Comment by iainrussell** [comment]
Hello @alkhwarizmi,

We are not often testing on Windows, but just now I created and activated a fresh conda environment on a Windows laptop and installed cfgrib with this command:
```
conda install cfgrib -c conda-forge
```
It resolved the dependencies within 10 seconds or so, and the installation was done within a minute. It might be that you are using an existing conda environment that has certain versions of packages installed that are not compatible with cfgrib, so I suggest you try with a newly created conda environment to see if that helps.

Do let us know if this works for you please!

Best regards,
Iain

**Comment by alkhwarizmi** [comment]
Dear Iain,

thanks for your kind reply. First of all I would like to say, for the records, that my second attempt with `channel_priority` equal to `false` also did not work.

What I did I then, in line with your suggestion, was updating the entire Anaconda repository with `conda update --all`. Then I installed cfgrib with `conda install cfgrib`. I think on my machines `-c conda-forge` is not strictly needed because conda has been informed already that I need packages from that source. This worked (although it took more than one minute).

So, my problem is now solved, but I couldn't really understand what was the package causing the problem nor why the system could not find a path to solve the conflicts. The fact that at the end I was able to install cfgrib, proves that such a path existed.

Sincerely,

**Comment by iainrussell** [comment]
OK, thanks for letting me know - glad it worked! I'll admit that I have also seen situations where conda could not manage to resolve dependencies (not specifically with cfgrib) and it can indeed be a nightmare!

I'll close this issue now, as I don't think it's something that can really be fixed on our side.

Best regards,
Iain
