### ISSUE TITLE
Alternate scanning directions not honored in NBM GRIB files

### ISSUE THREAD

**Issue by jsillin** [ecmwf/cfgrib#276]
I was attempting to read some NBM (National Blend of Models) GRIB files using xarray and cfgrib:
`    t_ds = xr.open_dataset('blend.t12z.core.f%03d.co.grib2'%12, filter_by_keys={'stepType': 'instant', 'typeOfLevel': 'surface','paramId':130})
`
The reading operation was successful in that it didn't throw an error... but it also ended up looking really screwy when I went to make a very quick plot `t_ds['t'].plot()`:
![nbm_gribreadfail](https://user-images.githubusercontent.com/40693187/150642138-5e74c404-d1bd-4ea0-861d-847e867b686a.png)

The twitter hive mind (thread for reference: https://twitter.com/JackSillin/status/1484617258852888582) quickly assessed that this was due to cfgrib not honoring some flag/option in the NBM GRIBs that reads the rows in the alternating order in which they were written. I've only ever had this issue with NBM gribs (to replicate the issue you may want to find yourself one or two https://noaa-nbm-grib2-pds.s3.amazonaws.com/index.html#blend.20220121/12/core/).

**Comment by shahramn** [comment]
I think there may be an issue with the ecCodes library (the GeoIterator for Polar Stereographic projection).

**Comment by shahramn** [comment]
This will be fixed in ecCodes v2.25.0, which will most likely be released in February

**Comment by shahramn** [comment]
ecCodes v2.25.0 has been released. See https://confluence.ecmwf.int/display/ECC/ecCodes+version+2.25.0+released

**Comment by cameronbracken** [comment]
This doesn't seem to be fixed. I'm using ecCodes v2.27.0 and I still get the same graphic as above when I try and plot.

**Comment by iainrussell** [comment]
Hi @cameronbracken, try the master branch of cfgrib if you can, that has a fix for alternate scanning. #296

**Comment by cameronbracken** [comment]
Thanks for the tip, I was able to get things working by manually installing cfgrib. Any idea when this will make it way to conda-forge/pypi?

**Comment by iainrussell** [comment]
Excellent! I think we could schedule a release for this coming week, as there are some important issues that have been fixed.

**Comment by iainrussell** [comment]
Hi @cameronbracken, cfgrib 0.9.10.2 is now on pypi and conda-forge!

**Comment by cameronbracken** [comment]
Thank you! I did a fresh install from conda-forge and everything works as expected.

**Comment by iainrussell** [comment]
That's great, thanks for letting me know!
