### ISSUE TITLE
Do not use relpath?

### ISSUE THREAD

**Issue by floriankrb** [ecmwf/cfgrib#284]
This use of relpath :  

https://github.com/ecmwf/cfgrib/blob/3a53b3a74bef80557d630f5eea2ba05934f07383/cfgrib/messages.py#L552

is causing an issue on window when path and start are on different drives.

Indeed in the os.path.relpath documentation:

    Return a relative filepath to path either from the current directory or from an optional start directory. 
    This is a path computation: the filesystem is not accessed to confirm the existence or nature of path or start. 
    On Windows, [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) is raised 
    when path and start are on different drives.

This happens in real use cases:

https://github.com/Climdyn/climetlab-eumetnet-postprocessing-benchmark/runs/5217438193?check_suite_focus=true#step:8:508

  ValueError: path is on mount 'C:', start on mount 'D:'

Perhaps a try/catch would help here?

**Comment by iainrussell** [comment]
Hi @floriankrb,

So what's the correct thing to do here? Something like this?
```
def source(self) -> str:
    try:
        return os.path.relpath(self.fieldset.path)
    except ValueError:
        return self.fieldset.path
```

**Comment by alexamici** [comment]
@iainrussell your fix is one possibility, the other option is to return `"N/A"`.

The idea after the `relpath` is that the source is written in the `history` attribute and it may end up leaking the folder structure of the machine (possibly including the user home folder and username) in a netCDF file. This is especially a problem in production environments.

**Comment by floriankrb** [comment]
Yes, I think that any of these two solutions would work. 

I would go for what @iainrussell proposed, based on the (very biased) assumption that if you use windows in a production environment, security and information leak are not your main concern.

**Comment by iainrussell** [comment]
Actually, after reading what @alexamici wrote, I think I'm more inclined to return `basename(path)` in this case, so we get the filename of the GRIB file. In many cases this is probably what `relpath(path)` would return anyway.
