### ISSUE TITLE
failed to set key 'endStep' in to_grib

### ISSUE THREAD

**Issue by jiaobf** [ecmwf/cfgrib#289]
I read the temperature from GFS and tried to write the data to a new GRIB file .
```
from eccodes import *
import numpy as np
import xarray as xr 
from cfgrib.xarray_to_grib import to_grib

filename = "gfs.2022010500f24"
ds = xr.open_dataset(filename, engine='cfgrib',
                     backend_kwargs={'filter_by_keys': {'typeOfLevel': 'isobaricInhPa', 
                                                        'name'       : 'Temperature'}})

to_grib(ds, 'out1.grib', grib_keys={'edition': 2})
```

Running the script directly will result in an error
```
KeyError: 1641340800000000000
```
following #272 , it works with a warning :
```
failed to set key 'endStep' to numpy.timedelta64(24,'ns')
```
and the time information in the grib file is incorrect

```
1:0:d=2022010500:TMP Temperature [K]:1000 mb:anl:
```
which should be 
```
542:117403445:d=2022010500:TMP Temperature [K]:1000 mb:24 hour fcst:
```

**Environment:**
Python 3.8 from conda-forge on centos7

pandas                    1.3.4
cfgrib                    0.9.9.1
xarray                    0.20.1

**Comment by ChristopheLRTE** [comment]
Hello, where could we find the gfs.2022010500f24 file ?

**Comment by jiaobf** [comment]
> Hello, where could we find the gfs.2022010500f24 file ?

Thank you for your attention. GFS file can be download with
```
wget https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20220228/00/atmos/gfs.t00z.pgrb2.0p50.f024
```
in which gfs.YYYYMMDD/00 can be set to any day in the past week.

**Comment by jiaobf** [comment]
> This should be fixed with the release of the next eccodes-python, which now accepts numpy.int64 for setting keys: https://github.com/ecmwf/eccodes-python/commits/develop You can either try the develop branch of eccodes-python, or wait for the release, which should be in a couple of days.

I manually modified line 973 and line 2063 of gribapi/gribapi.py , but it didn't seem to work.

**Comment by iainrussell** [comment]
Ah, do this change as well:
https://github.com/ecmwf/cfgrib/commit/3cc01e395cd66a376a279c0c603cbedcaeda7f50

**Comment by iainrussell** [comment]
Also, make sure you're using cfgrib from the master branch - this fix was important but is not yet in a release: https://github.com/ecmwf/cfgrib/commit/3cc01e395cd66a376a279c0c603cbedcaeda7f50
