### ISSUE TITLE
Handling of missing values

### ISSUE THREAD

**Issue by huanglangwen** [ecmwf/cfgrib#304]
When loading grib files with values around 9999, those values are masked to np.nan by cfgrib in the following line:

https://github.com/ecmwf/cfgrib/blob/0834b19d56ab2a817cc5a3309149806afdcf0ced/cfgrib/dataset.py#L358

Is there a way to set missing values manually to avoid this case?

Thanks a lot!

**Comment by huanglangwen** [comment]
Thank you! But setting `missingValue` to the grib file has a lot of overheads as we have 100GB+ grib files and there's no way to set it inplace. I'm wondering if cfgrib can provide an option to override the `missingValue` setting like the `grib_get_data -m` does.

**Comment by iainrussell** [comment]
Thank you for this report - indeed, I think we need to make a change in the internals of cfgrib to use an 'out of range' missing value indicator. Stay tuned!

**Comment by iainrussell** [comment]
Fixed - same resolution as for #313
