### ISSUE TITLE
Ignoring index file

### ISSUE THREAD

**Issue by wangys666** [ecmwf/cfgrib#307]
Hello. When use cfgrib to open GFS grib files, mulitple warnings  shows like:
Ignoring index file 'gfs.t12z.pgrb2.0p25.f005.923a8.idx' incompatible with GRIB file.

After warnings, the code still works.
A issue mentioned the same problem before, upgraded cfgrib version to 0.9.10 can solve that problem, but don't work for me.

my package version:

cfgrib =0.9.10.1
eccodes=2.26.0
xarray =2022.6.0

my code like:
```
f = cfgrib.open_datasets(file,
                             backend_kwargs={'filter_by_keys': {'typeOfLevel': 'heightAboveGround'}})
```

**Comment by iainrussell** [comment]
You're welcome, glad you got it working!
