### ISSUE TITLE
Quickly Combining grib files in windows

### ISSUE THREAD

**Issue by lassiterdc** [ecmwf/cfgrib#309]
I have hundreds of thousands of grib files each representing a single two-minute timestep that I'd like to ultimately combine unto daily netcdfs. The go-to suggestion for this seems to be to use the `cat` command, then load the dataset with [`xarray.open_mfdataset()`](https://docs.xarray.dev/en/stable/generated/xarray.open_mfdataset.html), and then call [`xarray.dataset.to_netcdf()`](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.to_netcdf.html). However, `cat` , as far as I understand, does not have a windows counterpart. This means I have to go straight to [`xarray.open_mfdataset()`](https://docs.xarray.dev/en/stable/generated/xarray.open_mfdataset.html) which takes a nearly prohibitively long time given the number of gribs I need to load. Is there any faster way of doing this on a windows machine?

Data: [Dropbox link](https://www.dropbox.com/sh/5md27sohpfpox4u/AADwNRxiBN0pWro_V3x0cMPSa?dl=0) to 10 grib files each representing a 2-minute timestep of radar rainfall data in the continental US (9.6 MB)

Code:
```python
import xarray as xr

fpath_gribs = "gribs/*.grib2"

%time ds = xr.open_mfdataset(fpath_gribs, engine="cfgrib")
```

Output:
```python
CPU times: total: 1min 29s
Wall time: 1min 29s
```

Environment:
```
Windows 11
python 3.8.13
cfgrib 0.9.10.1
xarray 2022.6.0
```

**Comment by shahramn** [comment]
How about this?
https://superuser.com/questions/434870/what-is-the-windows-equivalent-of-the-unix-command-cat

**Comment by lassiterdc** [comment]
I tried this and unfortunately it didn't work. A `temp.grib2` file was generated, but it had no data. 

I am able to use the cat command in PowerShell so I could write a separate script to do this which is definitely workable, but it's not as tidy as I was aiming for.

```python
import xarray as xr
fpath_gribs = "gribs/*.grib2"
os.system('type {} > temp.grib2'.format(fpath_gribs))
ds = xr.open_mfdataset("temp.grib2", engine="cfgrib")
```

**Comment by iainrussell** [comment]
Perhaps some pure Python would do it, e.g. https://stackoverflow.com/questions/25911224/append-binary-file-to-another-binary-file

**Comment by lassiterdc** [comment]
That appears to be working, thank you so much!!!

**Comment by iainrussell** [comment]
Cool, thanks for letting us know!
