### ISSUE TITLE
Add `rotated_ll` support

### ISSUE THREAD

**Issue by alexamici** [ecmwf/cfgrib#35]
As reported by @guidocioni GRIB files in the `gridType==rotated_ll` can be structured as 2D like `lambert`.

Example files in: https://opendata.dwd.de/weather/nwp/cosmo-d2-eps/grib/00/t_2m/

**Comment by alexamici** [comment]
Close on 29afe28a1e5150f3e1ec72d9d34b001d6bcbe07e

**Comment by jodemaey** [comment]
Hi @alexamici , sorry this is maybe this is a stupid question, but does that mean that cfgrib is also doing the u v wind components rotation (through eccodes?) ?

I could not find any reference about that elsewhere.

Thank you in advance,

Jonathan
