### ISSUE TITLE
broken link in example grib file in github Readme "Usage" section

### ISSUE THREAD

**Issue by Timothy-W-Hilton** [ecmwf/cfgrib#365]
### What maintenance does this project need?

The link to download a well-formed grib file in the first sentence of the [Usage section](https://github.com/ecmwf/cfgrib#usage) of the [cfgrib GitHub repository](https://github.com/ecmwf/cfgrib) seems to be broken:

`
└─[$] wget http://download.ecmwf.int/test-data/cfgrib/era5-levels-members.grib                                                                                                     
--2024-01-17 10:56:28--  http://download.ecmwf.int/test-data/cfgrib/era5-levels-members.grib
Resolving download.ecmwf.int (download.ecmwf.int)... 136.156.180.69
Connecting to download.ecmwf.int (download.ecmwf.int)|136.156.180.69|:80... failed: Connection refused.
`
I get the same result using curl or typing the URL into my browser

### Organisation

GNS Science, Te Pū Ao

**Comment by shahramn** [comment]
The correct link is:
```
wget  https://get.ecmwf.int/repository/test-data/cfgrib/era5-levels-members.grib
```

Thanks for bringing that to our attention
