### ISSUE TITLE
Wrong latitude and longitude

### ISSUE THREAD

**Issue by fedecutraro** [ecmwf/cfgrib#368]
### What happened?

Hello,
I'm trying to use cfgrib to open a grib file created with the Unified Post Processor ([UPP](https://dtcenter.org/community-code/unified-post-processor-upp)) but the latitudes and longitudes I get are wrong. The domain has to be over Argentina and for example, the latitudes are from the northern hemisphere.

When I use pygrib or Panoply to open the same file the latitudes and longitudes are correct.

### What are the steps to reproduce the bug?

`import xarray as xr`
`ds = xr.open_dataset('wrfprs_20240205_0000.012', engine = 'cfgrib')`
`print(ds['latitude'].values)`

### Version

0.9.10.1

### Platform (OS and architecture)

Red Hat Enterprise Linux Server 7.6 (Maipo)

### Accompanying data

https://drive.google.com/file/d/1PUN9YqLHmBkw1Y7ymryhOKZZGzRC4HE2/view?usp=sharing

**Comment by shahramn** [comment]
This is a problem in the ecCodes Geoiterator for Lambert Conformal grids in the southern hemisphere. I will start working on a fix.
Thanks for reporting this issue

**Comment by shahramn** [comment]
This has now been fixed and will be released as part of ecCodes
