### ISSUE TITLE
Longitude values greater than 360

### ISSUE THREAD

**Issue by malmans2** [ecmwf/cfgrib#388]
### What happened?

When `cfgrib` is used with `eccodes >= 2.35.0`, the snippet below returns longitude values greater that 360.
I'm not sure whether this is an issue to fix in eccodes or cfgrib, so I'm opening a ticket for both libraries.

### What are the steps to reproduce the bug?

```python
import cdsapi
import xarray as xr

client = cdsapi.Client()

collection_id = "reanalysis-carra-single-levels"
request = {
    "level_type": "surface_or_atmosphere",
    "variable": "2m_temperature",
    "product_type": "analysis",
    "time": ["00:00"],
    "domain": "east_domain",
    "month": "12",
    "day": ["01"],
    "year": ["1990"],
}

filepath = client.retrieve(collection_id, request).download()
ds = xr.open_dataset(filepath)

assert (ds["longitude"] <= 360).all()
```

### Version

0.9.13.0

### Platform (OS and architecture)

Darwin MacBook-Pro-3.local 22.6.0 Darwin Kernel Version 22.6.0: Mon Apr 22 20:54:28 PDT 2024; root:xnu-8796.141.3.705.2~1/RELEASE_X86_64 x86_64

### Organisation

B-Open / CADS-EQC

**Comment by shahramn** [comment]
This is a bug in the ecCodes Geoiterator for the Lambert Conformal grid. I will fix it in the next release.
Many thanks
