### ISSUE TITLE
ecCodes version 2.36.0 

### ISSUE THREAD

**Issue by MargaridaBSC** [ecmwf/cfgrib#404]
Dear cfgrib Team,
I contact you because I would like to install the version 2.36.0 for ecCodes in order to do the cfgrib conversion from grib files to netcdf like it is done at CDS, for example:
```
ncdump -h tas_20150101.nc-cds | grep history
                :history = "2024-10-18T10:36 GRIB to CDM+CF via cfgrib-0.9.14.1/ecCodes-2.36.0 with {\"source\": \"data.grib\", \"filter_by_keys\": {\"centre\": \"kwbc\"}, \"encode_cf\": [\"parameter\", \"time\"
, \"geography\", \"vertical\"]}" 
```
 I achieved to install cfgrib version 0.9.14.1:
```
pip freeze | grep cfgrib 
cfgrib==0.9.14.1
```
but when trying to install version 2.36.0 for ecCodes the next error appears:
```
pip install ecCodes==v2.36.0
ERROR: Could not find a version that satisfies the requirement ecCodes==v2.36.0 (from versions: 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 1.7.1, 2.37.0, 2.38.0, 2.38.1, 2.38.3)
ERROR: No matching distribution found for ecCodes==v2.36.0
```
Please, could you take a look?

Thank you very much in advance.
Best regards,
Margarida

### Organisation

BSC

**Comment by iainrussell** [comment]
Hi @MargaridaBSC, the confusion here comes from the fact that prior to ecCodes 2.37.0, you had to install it as two separate packages.

First, you had the ecCodes binary library, which you could install from conda or brew (some instructions [here](https://github.com/ecmwf/eccodes-python)). You would find ecCodes 2.36.0 there (or you can get the source code from GitHub and build it yourself if you're familiar with such things).

Second, you would install the Python bindings. Prior to ecCodes 2.37.0, these had much smaller version numbers such as 1.7.0, and lived an almost separate life.

As of ecCodes 2.37.0, we [started](https://confluence.ecmwf.int/pages/viewpage.action?pageId=445299545) bundling the binary library with the Python bindings, and the bindings changed version number from 1.7.1 to 2.37.0 to match the binary version.

So... to get ecCodes 2.36.0, you will need to:
* install the ecCodes binaries, version 2.36.0
* install the Python bindings - if version 2.37.0 or above, set the environment variable ECCODES_PYTHON_USE_FINDLIBS=1; if the version of the Python bindings is below 2.37.0, then you will not need to set this env var
