### ISSUE TITLE
Missing CODES_MISSING_LONG, CODES_MISSING_DOUBLE constants

### ISSUE THREAD

**Issue by calmomau** [ecmwf/cfgrib#47]
It would be useful to be able to access the following constants defined in ecCodes from cfgrib:

- GRIB_MISSING_LONG, GRIB_MISSING_DOUBLE (defined in ecCodes grib_api.h)
- CODES_MISSING_LONG, CODES_MISSING_DOUBLE (defined in ecCodes eccodes.h)

**Comment by alexamici** [comment]
Added the `GRIB_` and `CODES_` variants.
