### ISSUE TITLE
Define last Python2 compatible version and follow xarray in being Python3 only.

### ISSUE THREAD

**Issue by alexamici** [ecmwf/cfgrib#69]
Starting from version 0.9.7 *cfgrib* is  Python3 only in line with *xarray* 0.12.0.

We intend to release additional bugfix only versions of the Python 2 compatible branch https://github.com/ecmwf/cfgrib/tree/stable/0.9.6.x

**Comment by djhoese** [comment]
FYI You can help PyPI/pip with this by specifying `python_requires` in your `setup.py`. If you make one more python 2 release with this set, then when you drop python 2 support, python 2 users should not be able to download the new python 3 only package.

**Comment by alexamici** [comment]
@djhoese I didn't know `python_requires`, I'll add it, thank you!

**Comment by alexamici** [comment]
We have the first release for Python 3 only version 0.9.7.

I close the issue.
