### ISSUE TITLE
Add support of recent versions of Windows

### ISSUE THREAD

**Issue by alexamici** [ecmwf/cfgrib#7]
At the moment *cfgrib* supports only Linux and MacOS.

For Windows we need:
 - [x] ecCodes support (experimental)
 - [x] CFFI support and DLL search capabilities
 - popular Python distributions
   - [x] conda
 - loose ends
   - [ ] write support (fix needed in *ecCodes*)
   - [x] broken `.idx` locking

**Comment by jlandmann** [comment]
Hi!
First of all: thanks for the great work you're doing!

I just wanted to ask out of curiosity if this issue something that has high priority for you or if you have kind of a "time schedule" of implementation. Background: I am writing a Python model that should run on both Windows & Linux, and GRIB support via Python on Windows seems to be something that is not yet possible without major hacks.

**Comment by kikocorreoso** [comment]
@jlandmann 
In case it is useful, in Windows I use GDAL tools to do some stuff with GRIB files.

@alexamici 
For me it would be interesting to know the plans for the windows versions. Are there any stuff we can help with eccodes or cfgrib on Windows?
Context: in the office I have to deal with Windows (7/10 - 32/64 bits) with limited admin rights so VC++ es complicated, Windows Subsystem for Linux is capped, Docker is not possible,... My only option nowadays is GDAL and Conda-forge to work with some GRIB related stuff on windows.

Thanks for the hard work with all the meteo related tools you are working on.

**Comment by vciulei** [comment]
hi @kikocorreoso ,

Would you mind sharing what are you using in order to decode GRIB files on windows x64? 
I am also investigating using MetView for this matter, will update.

Tks

**Comment by jlandmann** [comment]
Thanks @kikocorreoso, and sorry for the late reply. That's a good hint! I've tried to read in COSMO predictions in GDAL, it is throwing an error though - but that seems to be file-related.

@vciulei without wanting to speak in the name of @kikocorreoso, one option under Python is something like this:

    from osgeo import gdal

    data = gdal.Open('C:\\Path\\to\\gribfile')`

**Comment by kikocorreoso** [comment]
@vciulei 

Here is basic example to read mslp from a GFS file:

```python
from osgeo import gdal

grib = gdal.Open("gfs.t00z.pgrb2.0p25.anl", gdal.GA_ReadOnly)
b = grib.GetRasterBand(1)
mslp = b.ReadAsArray()
```

Some relevant info:
* https://www.gdal.org/frmt_grib.html
* A more complete example: https://gis.stackexchange.com/questions/289314/using-gdal-to-read-data-from-grib-file-in-python

**Comment by alexamici** [comment]
@jlandmann @kikocorreoso and @vciulei I have no timeline at the moment and I'm not going to have details in the future as I don't plan to work on the issue myself. According to @StephanSiemen who had looked into this, the main problem is that *ecCodes* itself can be forced to compile on *Windows* but only with serious effort. ECMWF aims to provide full *windows* support in *ecCodes*, but I have no idea of when.

On a brighter note. If anybody manages to build *ecCodes* on *Windows* they may just need to test what name to add to the list of library names here: https://github.com/ecmwf/cfgrib/blob/master/cfgrib/eccodes.py#L50

**Comment by jlandmann** [comment]
Thanks @alexamici for the clarification!
In fact I (think I) managed to compile some working x64 `.exe`s in Visual Studio as described in your online instructions and I found the lines you cited above, because I bumped into them when trying to open the grib file. I'll play a bit around and make a PR if I found something that works for me.

**Comment by vciulei** [comment]
@kikocorreoso @alexamici thank you both for the updates and the suggestions. 
@jlandmann looking forward, keep up the good work

**Comment by alexamici** [comment]
@jlandmann that would be great!

**Comment by alexamici** [comment]
📢📢📢 *ecCodes* can be installed on Windows with *conda*:

```
> conda install -c conda-forge eccodes
```

And *cfgrib* works almost out of the box! 🎊 

I'll be tying up loose ends in the next few days and release a version with full (read-only) Windows support soon.

**Comment by jlandmann** [comment]
Sorry that I didn't get back to you anymore! I accidentally overwrote the *.exes I produced and then it never worked anymore...:/
Therefore I'm even happier to hear the good news! :-)

**Comment by kikocorreoso** [comment]
@alexamici @StephanSiemen 

Thanks for the effort and the huge work!!!

Working with compilers on windows (enterprise capped windows environment in my case) is a real pain 😞

**Comment by vciulei** [comment]
@alexamici @StephanSiemen This is great news! Thank you for your effort!

**Comment by alexamici** [comment]
Well, ensuring full read-only Windows support in *cfgrib* amounted to adding a single line of code in an obscure error path, so kudos really need to go to ECMWF @StephanSiemen and @shahramn for pushing the ecCodes porting effort and to the CFFI developers for making writing portable bindings dead simple 😄 

Write support as well would have been 100% functional out of the box if was not for a path portability bug in the current version of *ecCodes*.

**Comment by albert-antony** [comment]
@alexamici cfgrib version installed on windows using the command 
> conda install -c conda-forge eccodes
works fine and does almost everything for basic analytical part. I am unable to extract certain parameters with cfgrib. I think pynio engine works fine for most part but it is not supported for windows versions.
