### ISSUE TITLE
"negative seek position" error

### ISSUE THREAD

**Issue by bertcoerver** [ecmwf/cfgrib#70]
I'm trying to open ERA5 pressure level data inside a grib-file downloaded from the CDS  (see the bottom of the post for the download-command).

I'm trying to open the data at different time-indices like this, which works fine for any value of t between 0 and 18:

```
ds = cfgrib.open_file(r'F:\era5_for_wam2\pl_2008_01.grib')
var = ds.variables['q']

t = 18
q = var.data[t,:,:,:]
```

However, as soon as t is larger than 18, e.g.:

`q = var.data[19,:,:,:]`

I get the following error:

```
Traceback (most recent call last):

  File "<ipython-input-30-a8a5f441ed1e>", line 1, in <module>
    q = var.data[19,:,:,:]

  File "C:\ProgramData\Miniconda3\lib\site-packages\cfgrib\dataset.py", line 259, in __getitem__
    message = self.stream.message_from_file(file, offset=offset[0])

  File "C:\ProgramData\Miniconda3\lib\site-packages\cfgrib\messages.py", line 244, in message_from_file
    return self.message_class.from_file(file=file, offset=offset, **kwargs)

  File "C:\ProgramData\Miniconda3\lib\site-packages\cfgrib\messages.py", line 66, in from_file
    file.seek(offset)

ValueError: negative seek position -5
```
I have many files like the one in this example (pl_2008_01.grib, pl_2008_02.grib, pl_2008_03.grib, etc.), and each of them crashes when trying to open data with a t > 18.

Any ideas what is causing this and how to solve this? I'm on a windows machine, Python=3.7.1 and cfgrib=0.9.6

I'm getting my grib files like this:

```
import cdsapi
c = cdsapi.Client()
c.retrieve(
            'reanalysis-era5-pressure-levels',
            {
                'product_type':'reanalysis',
                'format':'grib',
                'pressure_level':[
                    '50','150','250','350',
                    '450','550','650',
                    '750','800','850',
                    '900','950','1000'
                ],
                'month':'1',
                'day':[
                '01','02','03',
                '04','05','06',
                '07','08','09',
                '10','11','12',
                '13','14','15',
                '16','17','18',
                '19','20','21',
                '22','23','24',
                '25','26','27',
                '28','29','30',
                '31'
            ],
                'time':
                    [
                    '00:00','01:00','02:00',
                    '03:00','04:00','05:00',
                    '06:00','07:00','08:00',
                    '09:00','10:00','11:00',
                    '12:00','13:00','14:00',
                    '15:00','16:00','17:00',
                    '18:00','19:00','20:00',
                    '21:00','22:00','23:00',],
                'year':'2008',
                'variable':[
                    'specific_humidity','u_component_of_wind','v_component_of_wind',
                    'vertical_velocity'
                ]
            },
            r'F:\era5_for_wam2\pl_2008_01.grib')
```

**Comment by alexamici** [comment]
Thanks for the very well-written bug report. I'm quite surprised by the error because I'm using *cfgrib* heavily with ERA5 data and I've never triggered it.

I can think of only two possible reasons: Windows and a recent update in the indexing code.

Can you please verify if you can trigger the same bug with an earlier version of *cfgrib*? You would need to `pip install cfgrib==0.9.5.7` remove the `*.idx` files and try again.

Thanks.

**Comment by bertcoerver** [comment]
Ok I downgraded, still getting the same error when running:

```
print(cfgrib.__version__)
ds = cfgrib.open_file(r'F:\era5_for_wam2\pl_2008_01.grib')
var = ds.variables['q']

# this works
q = var.data[18,:,:,:]
print("succes")

# this gives an "ValueError: negative seek position -5"
q = var.data[19,:,:,:]
```

I get:

```
0.9.5.7
succes
Traceback (most recent call last):

  File "<ipython-input-6-76c4848a4edc>", line 10, in <module>
    q = var.data[19,:,:,:]

  File "C:\ProgramData\Miniconda3\lib\site-packages\cfgrib\dataset.py", line 259, in __getitem__
    message = self.stream.message_from_file(file, offset=offset[0])

  File "C:\ProgramData\Miniconda3\lib\site-packages\cfgrib\messages.py", line 231, in message_from_file
    return self.message_class.from_file(file=file, offset=offset, **kwargs)

  File "C:\ProgramData\Miniconda3\lib\site-packages\cfgrib\messages.py", line 63, in from_file
    file.seek(offset)

ValueError: negative seek position -5
```

**Comment by alexamici** [comment]
I downloaded the GRUB file from the CDS (75Gb!) and I cannot reproduce the problem neither on MacOS nor on a Windows 10 VM.

All data access works as expected.

How did you install ecCodes? Do you have any hint on what can be special on your setup?

**Comment by bertcoerver** [comment]
I'm using windows 7 (not really my choice), could that cause problems?

**Comment by bertcoerver** [comment]
Just in case anyone else has this problem:

I had installed  ecCodes with conda-forge with:

`conda install -c conda-forge eccodes`

but I didn't set the environmental variables ECCODES_DEFINITION_PATH and ECCODES_SAMPLES_PATH (see [here](https://confluence.ecmwf.int/pages/viewpage.action?pageId=70949236) for more info) correctly. Doing that solved the issue.

**Comment by bertcoerver** [comment]
Seems like I was cheering a bit too soon unfortunately. 

Initially, this happened at the time-index 19 (as described in my first post), now it seems to happen around t = 35. In my case I can solve it by just using smaller grib-files, but the solution I gave doesn't seem to be the solution after all.

**Comment by alexamici** [comment]
@bertcoerver:

1. Did you remove the `.idx` file and retry?
2. After doing 1. and still getting a `negative seek` error, can you attach the `.idx` file to the issue?

Thanks!

**Comment by tianrenzhang** [comment]
Exactly the same error, offset is -5.
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[16], [line 1](vscode-notebook-cell:?execution_count=16&line=1)
----> [1](vscode-notebook-cell:?execution_count=16&line=1) xe['p71.162'][10000].to_numpy()

File ~\.conda\envs\gis\lib\site-packages\xarray\core\dataarray.py:832, in DataArray.to_numpy(self)
    821 def to_numpy(self) -> np.ndarray:
    822     """
    823     Coerces wrapped data to numpy and returns a numpy.ndarray.
    824 
   (...)
    830     DataArray.data
    831     """
--> [832](file:///~/.conda/envs/gis/lib/site-packages/xarray/core/dataarray.py:832)     return self.variable.to_numpy()

File ~\.conda\envs\gis\lib\site-packages\xarray\namedarray\core.py:861, in NamedArray.to_numpy(self)
    859 """Coerces wrapped data to numpy and returns a numpy.ndarray"""
    860 # TODO an entrypoint so array libraries can choose coercion method?
--> [861](~/.conda/envs/gis/lib/site-packages/xarray/namedarray/core.py:861) return to_numpy(self._data)

File ~\.conda\envs\gis\lib\site-packages\xarray\namedarray\pycompat.py:112, in to_numpy(data, **kwargs)
    109     pass
    111 if isinstance(data, ExplicitlyIndexed):
--> [112](file:///~/.conda/envs/gis/lib/site-packages/xarray/namedarray/pycompat.py:112)     data = data.get_duck_array()  # type: ignore[no-untyped-call]
    114 # TODO first attempt to call .to_numpy() once some libraries implement it
...
---> [94](file:///~/.conda/envs/gis/lib/site-packages/cfgrib/messages.py:94)     file.seek(offset)
     95 codes_id = None
     96 if field_in_message == 0:

OSError: [Errno 22] Invalid argument

Exactly the same issue on Windows 11 and Windows 10. I haven't tried Ubuntu yet. Not only one GRIB files, but 3 GRIB files all produce this issue. It works for the first 4GB and this exception is raised near 2^32.
