### ISSUE TITLE
conda install cfgrib for py3.7?

### ISSUE THREAD

**Issue by mathause** [ecmwf/cfgrib#78]
Currently it is not possible to install `cfgrib` with conda for python 3.7. cfgrib has `typing` as dependency, which is not avaliable in py37. See

    conda search --info typing

As far as I know `typing` is in the standard library of py37. So this dependency can probably just be dropped for py37?

**Comment by mathause** [comment]
As a workaround it is possible to install it with

    conda install cfgrib --no-deps

and add the other dependencies manually. It seems to work, but of course lets conda complain about a broken environment.

**Comment by mathause** [comment]
A bit unrelated in the [Readme](https://github.com/ecmwf/cfgrib#read-only-xarray-grib-engine) you say `xarray >= 0.12.0` is required, while it is `xarray >=0.11.0` for conda, see

    conda search --info cfgrib

**Comment by alexamici** [comment]
Thanks, for spotting these two issues!

**Comment by alexamici** [comment]
Ok, I fixed the conda-forge repo, and the next version of *cfgrib* will be support only python 3.5 and up, so we will drop the dependency on the `typing` module as well.

I'll hurry up the release of version 0.9.7 that should fix both issues.

**Comment by mathause** [comment]
Thanks!

**Comment by alexamici** [comment]
Closing, I'm doing the release.
