### ISSUE TITLE
ValueError: sample not found: b'regular_ll_sfc_grib2'

### ISSUE THREAD

**Issue by yoyafish** [ecmwf/cfgrib#79]
**when I use spyder run these codes:**
```
import numpy as np
import xarray as xr
import cfgrib
ds2 = xr.DataArray(
     np.zeros((5, 6)) + 300.,
     coords=[
         np.linspace(90., -90., 5),
         np.linspace(0., 360., 6, endpoint=False),  ],     dims=['latitude', 'longitude'], ).to_dataset(name='skin_temperature')
ds2.skin_temperature.attrs['GRIB_shortName'] = 'skt'
cfgrib.to_grib(ds2, 'c:\\out2.grib')
xr.open_dataset('c:\\out2.grib', engine='cfgrib')
```
**fail with these errors:**
```
  File "d:\Anaconda3\lib\site-packages\cfgrib\messages.py", line 78, in from_sample_name
    codes_id = bindings.codes_new_from_samples(sample_name.encode('ASCII'), product_kind)
  File "d:\Anaconda3\lib\site-packages\cfgrib\bindings.py", line 448, in codes_new_from_samples
    raise ValueError("sample not found: %r" % samplename)
ValueError: sample not found: b'regular_ll_sfc_grib2'
```
**but these codes run success in jupyter,how should I deal with it?**

**Comment by alexamici** [comment]
@yoyafish I took the liberty to slightly reformat your description for clarity.

It looks like *cfgrib* doesn't find the `sample` folder of *ecCodes* when running inside *Spyder*.

One possibility for is that you start Spyder **outside** of the *conda* shell that sets up the environment variable used by *ecCodes* to find its configuration folders. Not sure if you have a way to run *Spyder* form the *conda* prompt.

If that fails please look for the function `portable_handle_new_from_samples` in `bindings.py` and change the exception handler to:
```
        try:
            with open(sample_path) as file:
                handle = codes_grib_new_from_file(file, product_kind)
        except Exception:
            raise  # was: pass
```
That should at least give us more hints.

**Comment by alexamici** [comment]
@yoyafish the report looks like temporary / installation problem so I'm going to close the issue, please reopen it if you have relevant updates.

**Comment by goncaloperes** [comment]
> Not sure if you have a way to run _Spyder_ form the _conda_ prompt.

We can open Spyder from conda prompt.

Assuming that one has Spyder installed in the environment that one is working with, one can simply run `spyder` (Note that if Spyder is already running, and if you want to open a new instance, please pass to it the --new-instance option).
