### ISSUE TITLE
JPEG support not enabled on Windows

### ISSUE THREAD

**Issue by maxdow** [ecmwf/cfgrib#80]
Hi, 
i want to read a grib2 file on windows coming from meteo france opendata but i got an error : 
```
ECCODES ERROR   :  JPEG support not enabled.
ECCODES ERROR   :  unable to get values as double array (Function not yet implemented)
ECCODES ERROR   :  unable to create iterator
```
I guess it's about dependencies and compilation because it is working on linux. Is there a way to resolve this ? 

PS : thanks for your work @alexamici  !

**Comment by alexamici** [comment]
@maxdow thanks!

This is not an issue with *crgrib* but, to my best knowledge, with the *ecCodes* recipe for *conda-forge*. You should report the issue here: https://github.com/conda-forge/eccodes-feedstock/issues

I'll close this issue.
