### ISSUE TITLE
Cannot generate idx file using sample grib file

### ISSUE THREAD

**Issue by hehuan710** [ecmwf/cfgrib#85]
import xarray as xr
ds = xr.open_dataset("era5-levels-members.grib",engine='cfgrib')
print(ds)

era5-levels-members.grib.011ab.idx  File size is 0KB

Can't read index file 'D:\\py_train\\era5-levels-members.grib.011ab.idx'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\cfgrib\messages.py", line 315, in from_indexpath_or_filestream
    self = cls.from_indexpath(indexpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cfgrib\messages.py", line 287, in from_indexpath
    return pickle.load(file)
EOFError: Ran out of input

**Comment by alexamici** [comment]
@hehuan710 I cannot reproduce this issue on my Windows 10 VM (via VirtualBox on MacOS). Please make sure it is not due to your local setup, permissions, etc.

Furthermore, if the creation of the `era5-levels-members.grib.011ab.idx` index file fails I would expect you to see an error message, can you remove the file, try again and report the error message if any?

**Comment by hehuan710** [comment]
@alexamici 
ECCODES ERROR : Unable to find boot.def. Context path=C:/bld/eccodes_1555087073004/_h_env/Library/share/eccodes/definitions

Possible causes:
‑ The software is not correctly installed
‑ The environment variable ECCODES_DEFINITION_PATH is defined but incorrect

ecCodes assertion failed: `0' in C:\bld\eccodes_1555087073004\work\src\grib_context.c:205

**Comment by hehuan710** [comment]
I set up the environment variable “ECCODES_DEFINITION_PATH” just fine. Thank you！

**Comment by Anudeep-S** [comment]
> I set up the environment variable “ECCODES_DEFINITION_PATH” just fine. Thank you！

@hehuan710 : This is my first interaction with GRIB and PyCharm too, and using a windows PC. Could you please let me know how can I set the environment variable “ECCODES_DEFINITION_PATH” in PyCharm. Thank you
