### ISSUE TITLE
Cannot find ECCODES_DEFINITON PATH using sample grib file in Windows

### ISSUE THREAD

**Issue by afDeathscythe** [ecmwf/cfgrib#87]
Hi,

this might be related to #85 but I have following problem:

I installed eccodes and cfgrib via Miniconda on Windows (works without any problems). After that I wanted to try out to read the grib file with following:

```python
import xarray as xr

ds = xr.open_dataset('era5-levels-members.grib', engine='cfgrib')
print(ds)
```

**I get the following error message:**

```python
ECCODES ERROR   :  Unable to find boot.def. Context path=C:/bld/eccodes_1555087073004/_h_env/Library/share/eccodes/definitions

Possible causes:
- The software is not correctly installed
- The environment variable ECCODES_DEFINITION_PATH is defined but incorrect

ecCodes assertion failed: `0' in C:\bld\eccodes_1555087073004\work\src\grib_context.c:205
```

I tried to set explicit the ECCODES_DEFINITON_PATH to Miniconda3\Library\share\eccodes\definitions in the Windows System Environment Variables settings. Still does not work. 

I don't know if I am doing something wrong here by setting the path.
Thanks for help & kind regards,

Marko

**Comment by afDeathscythe** [comment]
Ok can be closed, found out that I need to restart PyCharm that it is loaded into the PyCharm System Variables Environment^^ can be closed :)

**Comment by iainrussell** [comment]
Ok, thanks for letting us know that you solved it!

**Comment by MehrdadHMT** [comment]
> Ok can be closed, found out that I need to restart PyCharm that it is loaded into the PyCharm System Variables Environment^^

i have the same issue. can you tell what did you do exactly to solve it?!

**Comment by afDeathscythe** [comment]
> 
> 
> > Ok can be closed, found out that I need to restart PyCharm that it is loaded into the PyCharm System Variables Environment^^
> 
> i have the same issue. can you tell what did you do exactly to solve it?!

In Pycharm you can set Enviroment Variables in Edit Run Settings where it says PYTHONUNBUFFERED=1 for the program where you define e.g ECCODES_DEFINITON_PATH on the left and Miniconda3\Library\share\eccodes\definitions on the right and restart Pycharm.

Cheers,

Marko

**Comment by MehrdadHMT** [comment]
> > > Ok can be closed, found out that I need to restart PyCharm that it is loaded into the PyCharm System Variables Environment^^
> > 
> > 
> > i have the same issue. can you tell what did you do exactly to solve it?!
> 
> In Pycharm you can set Enviroment Variables in Edit Run Settings where it says PYTHONUNBUFFERED=1 for the program where you define e.g ECCODES_DEFINITON_PATH on the left and Miniconda3\Library\share\eccodes\definitions on the right and restart Pycharm.
> 
> Cheers,
> 
> Marko

thank you very much, it worked.

**Comment by amirmohammadmir** [comment]
> > > Ok can be closed, found out that I need to restart PyCharm that it is loaded into the PyCharm System Variables Environment^^
> > 
> > 
> > i have the same issue. can you tell what did you do exactly to solve it?!
> 
> In Pycharm you can set Enviroment Variables in Edit Run Settings where it says PYTHONUNBUFFERED=1 for the program where you define e.g ECCODES_DEFINITON_PATH on the left and Miniconda3\Library\share\eccodes\definitions on the right and restart Pycharm.
> 
> Cheers,
> 
> Marko

Although I did as you said, it did't solve my problem. What should I try?
