### ISSUE TITLE
cfgrib fails on a GRIB file with one corrupted message with no option to ignore it

### ISSUE THREAD

**Issue by meteoDaniel** [ecmwf/cfgrib#9]
I am trying to open IFS forecasting data (provided by knmi): 

`ds = xarray_store.open_dataset('ECMWF_DET_MCONTROL2_2018072912_009_GB')`

and got this error message: 

`EcCodesError: ('Wrong message length (-23).', -23)`

No problem to open the data with other EcCodes scripts e.g. 
`grib_get_data ECMWF_DET_MCONTROL2_2018072912_009_GB`

[ECMWF_DET_MCONTROL2_2018072912_009_GB.zip](https://github.com/ecmwf/cfgrib/files/2244249/ECMWF_DET_MCONTROL2_2018072912_009_GB.zip)

System settings: 
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux

and cfgrib version: 0.8.4.1

**Comment by alexamici** [comment]
One of the messages in the GRIB file appears to be corrupted:
```
$ grib_ls ECMWF_DET_MCONTROL2_2018072912_009_GB
ECMWF_DET_MCONTROL2_2018072912_009_GB
edition      centre       typeOfLevel  level        dataDate     stepRange    shortName    packingType  gridType     
1            ecmf         surface      0            20180729     9            2t           grid_simple  regular_ll  
		*** unreadable message ***
1            ecmf         surface      0            20180729     9            sd           grid_simple  regular_ll  
1            ecmf         surface      0            20180729     9            ssrd         grid_simple  regular_ll  
3 of 4 grib messages in ECMWF_DET_MCONTROL2_2018072912_009_GB

3 of 4 total grib messages in 1 files
```
We are more strict about errors than other tools. I leave the issue open as we may want to give users an option to be less strict.

**Comment by alexamici** [comment]
I added a `errors` keyword to `open_dataset` that controls what to do in case that a Message is corrupted, but ecCodes still doesn't crash. The default is to `ignore` the error and skip the messate. Old behaviour remain with `errors='strict'`.
