### ISSUE TITLE
kills kernell in python 3.7

### ISSUE THREAD

**Issue by DimaBryuhanov** [ecmwf/cfgrib#90]
Installed with conda install -m conda-forge - all went well including instalation of the dependancies and even the selfcheck showed that everything was OK.

However this code kills my python 3.7 kernell both in Jupyther and in Spyder.

This is the code:
----------------------------------------------------------------------------------------------------
import cfgrib

file = "sof-d.20190609.t00z.0p25.basic.europe.f000.grib2"
folder = "D:\\DATA\\maritime\\webinar 07.06.19\\09\\"

ds = cfgrib.open_datasets(folder + file)
print(ds)
----------------------------------------------------------------------------------------------------
Here's the result for the Notebook:
----------------------------------------------------------------------------------------------------
Can't read index file 'D:\\DATA\\maritime\\webinar 07.06.19\\09\\sof-d.20190609.t00z.0p25.basic.europe.f000.grib2.011ab.idx'
Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\lib\site-packages\cfgrib\messages.py", line 315, in from_indexpath_or_filestream
    self = cls.from_indexpath(indexpath)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\cfgrib\messages.py", line 287, in from_indexpath
    return pickle.load(file)
EOFError: Ran out of input
----------------------------------------------------------------------------------------------------

Here's the result for Spyder:
----------------------------------------------------------------------------------------------------
ECCODES ERROR : Unable to find boot.def. Context path=C:/bld/eccodes_1555087073004/_h_env/Library/share/eccodes/definitions

Possible causes:
‑ The software is not correctly installed
‑ The environment variable ECCODES_DEFINITION_PATH is defined but incorrect

ecCodes assertion failed: `0' in C:\bld\eccodes_1555087073004\work\src\grib_context.c:205
----------------------------------------------------------------------------------------------------

Please, kindly advise how this issue can be solved, since I urgently need a libruary to work with grib2 files. Thanks in advance for your kind assistance and for your great job supporting this library.

**Comment by alexamici** [comment]
The issue in Spyder is probably the same as #79 and #87 looks related as well.

Outside Spyder you can remove the `.idx` file and retry, if it still fails try passing `'indexpath': ''` to the `backend_kwargs` dict.

**Comment by alexamici** [comment]
@DimaBryuhanov both reported issues look like temporary / installation problems so I'm going to close the issue, please reopen it if you have relevant updates.

**Comment by holaaam** [comment]
Hi, here I have the same issue. I am really new to this. How did you solve it? I need to get it working urgently... Thanks

**Comment by Adamsim33** [comment]
I am also having this same issue. I noticed that the Eccodes error that says it cannot start the kernel is pointing to the D drive, yet my machine does not have a D drive. Is there a way to change where my Spyder session points to properly run Eccodes?

Here is my error:

ECCODES ERROR : Unable to find boot.def. Context path=D:/bld/eccodes_1603124531359/_h_env/Library/share/eccodes/definitions

Possible causes:
‑ The software is not correctly installed
‑ The environment variable ECCODES_DEFINITION_PATH is defined but incorrect

ecCodes assertion failed: `0' in D:\bld\eccodes_1603124531359\work\src\grib_context.c:226

**Comment by julienrobi3** [comment]
> I am also having this same issue. I noticed that the Eccodes error that says it cannot start the kernel is pointing to the D drive, yet my machine does not have a D drive. Is there a way to change where my Spyder session points to properly run Eccodes?
> 
> Here is my error:
> 
> ECCODES ERROR : Unable to find boot.def. Context path=D:/bld/eccodes_1603124531359/_h_env/Library/share/eccodes/definitions
> 
> Possible causes:
> ‑ The software is not correctly installed
> ‑ The environment variable ECCODES_DEFINITION_PATH is defined but incorrect
> 
> ecCodes assertion failed: `0' in D:\bld\eccodes_1603124531359\work\src\grib_context.c:226

Have you found an answer to your question? I have the exact same issue, pointing to an inexistant D:/. 
Thanks!

**Comment by iainrussell** [comment]
Hi,

It looks like this answer is relevant:
https://superuser.com/questions/1569216/eccodes-error-when-opening-grib-file-in-spyder-and-in-visual-studio-code

Cheers,
Iain

**Comment by huealu** [comment]
Hi, 

I am having an issue when open grib2 file as below. Does anyone has any solution?
I am using Python 3.8.5, eccodes 2.18.0 and cfgrib in Anaconda virtual environment to open grib2 file.

![image](https://user-images.githubusercontent.com/51888379/123848899-d651f700-d8dd-11eb-8170-93fe590360ba.png)

Thanks!

**Comment by soelemaafnan** [comment]
Having the same issue, has anybody found the solution?
