### ISSUE TITLE
Error cfgrib.to_grib convert netcdf to grib

### ISSUE THREAD

**Issue by taoansf** [ecmwf/cfgrib#91]
Hello,

I'm looking for a solution to write a grib file from a netcdf data using this code

#! /usr/bin/env python
import xarray as xa
import cfgrib
ds = xa.open_dataset('2015-01-15.nc')
cfgrib.to_grib(ds,'2015-01-15.grb', grib_keys={'gridType':'regular_ll'})

However python give me this error mensage

File "C:\Users\Usuario\Miniconda3\lib\site-packages\cfgrib\bindings.py", line 442, in portable_handle_new_from_samples
    sample_path = os.path.join(samples_folder, samplename + b'.tmpl')
TypeError: must be str, not bytes

This is my input file, from [SST-MUR](https://mur.jpl.nasa.gov/) data

[2015-01-15.zip](https://github.com/ecmwf/cfgrib/files/3307456/2015-01-15.zip)

I will appreciate any help with this problem.

With best regards,

Taoan

**Comment by alexamici** [comment]
@taoansf ouch! This is a typical [brown-paper-bag bug](https://lwn.net/1999/0204/kernel.php3). It appears only on Windows. Sorry!

I fixed it in the `develop` branch, I'll try to push a release ASAP. Thanks!

**Comment by taoansf** [comment]
Thank you @alexamici you are right, that error does not occur on my linux environment.

However, when I try to load the grib output  with this code it does not work
#! /usr/bin/env python
import xarray as xa
import cfgrib
ds1 = xa.open_dataset('2015-01-15.nc')
cfgrib.to_grib(ds1,'2015-01-15.grb', grib_keys={'gridType':'regular_ll'})
ds2=xa.open_dataset('2015-01-15.grb', engine='cfgrib')

Do you have some idea how to solve this?

With best regards,

Taoan

**Comment by taoansf** [comment]
This is the error message
![image](https://user-images.githubusercontent.com/22460776/60192991-45874300-980d-11e9-9c85-817ffbc332a9.png)

My grib output
[2015-01-15-grib.zip](https://github.com/ecmwf/cfgrib/files/3330799/2015-01-15-grib.zip)

**Comment by alexamici** [comment]
The problem it that in order to save arbitrary netCDF files to GRIB with *cfgrib* you must specify all the `grib_keys` that are not automatically computed. At the moment very few keys are computed and you need to set almost all the values as you would do with *ecCodes*.

Saving a to grib a GRIB file opened with *cfgrib* works more often because the dataset keeps the GRIB keys of the original file, but if you start from a netCDF you need to do the work manually and you need to know the GRIB data format.

**Comment by taoansf** [comment]
Thank you @alexamici, your explanation was very precise.
I will check eccodes documentation about the grib_keys to format my netcdf input.

With best regards,

Taoan
