### ISSUE TITLE
indexpath suppression should be supported in open_datasets

### ISSUE THREAD

**Issue by shipmints** [ecmwf/cfgrib#93]
Greetings and thank you for a wonderful library.

I'm using the latest version from pypi: cfgrib             0.9.7  

It seems that in xarray_store.py, the following code does not respect the indexpath that the calling code does?
```python
def open_variable_datasets(path, backend_kwargs={}, **kwargs):
    # could either skip this if indexpath is None or '' or pass it downward as open_fileindex does take indexpath arg.
    index = open_fileindex(path, filter_by_keys=backend_kwargs.get('filter_by_keys', {}))
```
In our situation, our grib files generally live in a location that's read only from the caller's perspective and we don't always need the performance boost of a pre-stored index. When we do, we can point indexpath to a "tmp" directory.

**Comment by alexamici** [comment]
Good catch. Thanks! I'll fix it ASAP.

**Comment by alexamici** [comment]
@shipmints please upgrade to version 0.9.7.1 on PyPI.

**Comment by shipmints** [comment]
@alexamici looks like it's working. Thank you.
